/*
 * cen
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.cen.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * RegionsForDescribeCenRegionsOutput
 */



public class RegionsForDescribeCenRegionsOutput {
  @SerializedName("GeographicRegionSetIds")
  private String geographicRegionSetIds = null;

  @SerializedName("RegionEnName")
  private String regionEnName = null;

  @SerializedName("RegionId")
  private String regionId = null;

  @SerializedName("RegionName")
  private String regionName = null;

  @SerializedName("RegionType")
  private String regionType = null;

  public RegionsForDescribeCenRegionsOutput geographicRegionSetIds(String geographicRegionSetIds) {
    this.geographicRegionSetIds = geographicRegionSetIds;
    return this;
  }

   /**
   * Get geographicRegionSetIds
   * @return geographicRegionSetIds
  **/
  @Schema(description = "")
  public String getGeographicRegionSetIds() {
    return geographicRegionSetIds;
  }

  public void setGeographicRegionSetIds(String geographicRegionSetIds) {
    this.geographicRegionSetIds = geographicRegionSetIds;
  }

  public RegionsForDescribeCenRegionsOutput regionEnName(String regionEnName) {
    this.regionEnName = regionEnName;
    return this;
  }

   /**
   * Get regionEnName
   * @return regionEnName
  **/
  @Schema(description = "")
  public String getRegionEnName() {
    return regionEnName;
  }

  public void setRegionEnName(String regionEnName) {
    this.regionEnName = regionEnName;
  }

  public RegionsForDescribeCenRegionsOutput regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public RegionsForDescribeCenRegionsOutput regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  @Schema(description = "")
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public RegionsForDescribeCenRegionsOutput regionType(String regionType) {
    this.regionType = regionType;
    return this;
  }

   /**
   * Get regionType
   * @return regionType
  **/
  @Schema(description = "")
  public String getRegionType() {
    return regionType;
  }

  public void setRegionType(String regionType) {
    this.regionType = regionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionsForDescribeCenRegionsOutput regionsForDescribeCenRegionsOutput = (RegionsForDescribeCenRegionsOutput) o;
    return Objects.equals(this.geographicRegionSetIds, regionsForDescribeCenRegionsOutput.geographicRegionSetIds) &&
        Objects.equals(this.regionEnName, regionsForDescribeCenRegionsOutput.regionEnName) &&
        Objects.equals(this.regionId, regionsForDescribeCenRegionsOutput.regionId) &&
        Objects.equals(this.regionName, regionsForDescribeCenRegionsOutput.regionName) &&
        Objects.equals(this.regionType, regionsForDescribeCenRegionsOutput.regionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geographicRegionSetIds, regionEnName, regionId, regionName, regionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionsForDescribeCenRegionsOutput {\n");
    
    sb.append("    geographicRegionSetIds: ").append(toIndentedString(geographicRegionSetIds)).append("\n");
    sb.append("    regionEnName: ").append(toIndentedString(regionEnName)).append("\n");
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    regionType: ").append(toIndentedString(regionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
