/*
 * vs20260714
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.vs20260714.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.vs20260714.model.NumberInfoListForCreateVoiceTaskInput;
import com.byteplus.vs20260714.model.VoiceContentForCreateVoiceTaskInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateVoiceTaskRequest
 */



public class CreateVoiceTaskRequest {
  @SerializedName("DisplayNum")
  private String displayNum = null;

  @SerializedName("MaxHangUpTime")
  private Integer maxHangUpTime = null;

  @SerializedName("MaxRingTime")
  private Integer maxRingTime = null;

  @SerializedName("NumberInfoList")
  private List<NumberInfoListForCreateVoiceTaskInput> numberInfoList = null;

  @SerializedName("RepeatingCount")
  private Integer repeatingCount = null;

  @SerializedName("SendTime")
  private String sendTime = null;

  @SerializedName("ServiceCode")
  private String serviceCode = null;

  @SerializedName("TaskId")
  private String taskId = null;

  @SerializedName("TaskName")
  private String taskName = null;

  @SerializedName("TimeZone")
  private String timeZone = null;

  @SerializedName("VoiceContent")
  private VoiceContentForCreateVoiceTaskInput voiceContent = null;

  public CreateVoiceTaskRequest displayNum(String displayNum) {
    this.displayNum = displayNum;
    return this;
  }

   /**
   * Get displayNum
   * @return displayNum
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getDisplayNum() {
    return displayNum;
  }

  public void setDisplayNum(String displayNum) {
    this.displayNum = displayNum;
  }

  public CreateVoiceTaskRequest maxHangUpTime(Integer maxHangUpTime) {
    this.maxHangUpTime = maxHangUpTime;
    return this;
  }

   /**
   * Get maxHangUpTime
   * @return maxHangUpTime
  **/
  @Schema(description = "")
  public Integer getMaxHangUpTime() {
    return maxHangUpTime;
  }

  public void setMaxHangUpTime(Integer maxHangUpTime) {
    this.maxHangUpTime = maxHangUpTime;
  }

  public CreateVoiceTaskRequest maxRingTime(Integer maxRingTime) {
    this.maxRingTime = maxRingTime;
    return this;
  }

   /**
   * Get maxRingTime
   * @return maxRingTime
  **/
  @Schema(description = "")
  public Integer getMaxRingTime() {
    return maxRingTime;
  }

  public void setMaxRingTime(Integer maxRingTime) {
    this.maxRingTime = maxRingTime;
  }

  public CreateVoiceTaskRequest numberInfoList(List<NumberInfoListForCreateVoiceTaskInput> numberInfoList) {
    this.numberInfoList = numberInfoList;
    return this;
  }

  public CreateVoiceTaskRequest addNumberInfoListItem(NumberInfoListForCreateVoiceTaskInput numberInfoListItem) {
    if (this.numberInfoList == null) {
      this.numberInfoList = new ArrayList<NumberInfoListForCreateVoiceTaskInput>();
    }
    this.numberInfoList.add(numberInfoListItem);
    return this;
  }

   /**
   * Get numberInfoList
   * @return numberInfoList
  **/
  @Valid
  @Schema(description = "")
  public List<NumberInfoListForCreateVoiceTaskInput> getNumberInfoList() {
    return numberInfoList;
  }

  public void setNumberInfoList(List<NumberInfoListForCreateVoiceTaskInput> numberInfoList) {
    this.numberInfoList = numberInfoList;
  }

  public CreateVoiceTaskRequest repeatingCount(Integer repeatingCount) {
    this.repeatingCount = repeatingCount;
    return this;
  }

   /**
   * Get repeatingCount
   * @return repeatingCount
  **/
  @Schema(description = "")
  public Integer getRepeatingCount() {
    return repeatingCount;
  }

  public void setRepeatingCount(Integer repeatingCount) {
    this.repeatingCount = repeatingCount;
  }

  public CreateVoiceTaskRequest sendTime(String sendTime) {
    this.sendTime = sendTime;
    return this;
  }

   /**
   * Get sendTime
   * @return sendTime
  **/
  @Schema(description = "")
  public String getSendTime() {
    return sendTime;
  }

  public void setSendTime(String sendTime) {
    this.sendTime = sendTime;
  }

  public CreateVoiceTaskRequest serviceCode(String serviceCode) {
    this.serviceCode = serviceCode;
    return this;
  }

   /**
   * Get serviceCode
   * @return serviceCode
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getServiceCode() {
    return serviceCode;
  }

  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }

  public CreateVoiceTaskRequest taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public CreateVoiceTaskRequest taskName(String taskName) {
    this.taskName = taskName;
    return this;
  }

   /**
   * Get taskName
   * @return taskName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTaskName() {
    return taskName;
  }

  public void setTaskName(String taskName) {
    this.taskName = taskName;
  }

  public CreateVoiceTaskRequest timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @Schema(description = "")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public CreateVoiceTaskRequest voiceContent(VoiceContentForCreateVoiceTaskInput voiceContent) {
    this.voiceContent = voiceContent;
    return this;
  }

   /**
   * Get voiceContent
   * @return voiceContent
  **/
  @Valid
  @Schema(description = "")
  public VoiceContentForCreateVoiceTaskInput getVoiceContent() {
    return voiceContent;
  }

  public void setVoiceContent(VoiceContentForCreateVoiceTaskInput voiceContent) {
    this.voiceContent = voiceContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVoiceTaskRequest createVoiceTaskRequest = (CreateVoiceTaskRequest) o;
    return Objects.equals(this.displayNum, createVoiceTaskRequest.displayNum) &&
        Objects.equals(this.maxHangUpTime, createVoiceTaskRequest.maxHangUpTime) &&
        Objects.equals(this.maxRingTime, createVoiceTaskRequest.maxRingTime) &&
        Objects.equals(this.numberInfoList, createVoiceTaskRequest.numberInfoList) &&
        Objects.equals(this.repeatingCount, createVoiceTaskRequest.repeatingCount) &&
        Objects.equals(this.sendTime, createVoiceTaskRequest.sendTime) &&
        Objects.equals(this.serviceCode, createVoiceTaskRequest.serviceCode) &&
        Objects.equals(this.taskId, createVoiceTaskRequest.taskId) &&
        Objects.equals(this.taskName, createVoiceTaskRequest.taskName) &&
        Objects.equals(this.timeZone, createVoiceTaskRequest.timeZone) &&
        Objects.equals(this.voiceContent, createVoiceTaskRequest.voiceContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayNum, maxHangUpTime, maxRingTime, numberInfoList, repeatingCount, sendTime, serviceCode, taskId, taskName, timeZone, voiceContent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVoiceTaskRequest {\n");
    
    sb.append("    displayNum: ").append(toIndentedString(displayNum)).append("\n");
    sb.append("    maxHangUpTime: ").append(toIndentedString(maxHangUpTime)).append("\n");
    sb.append("    maxRingTime: ").append(toIndentedString(maxRingTime)).append("\n");
    sb.append("    numberInfoList: ").append(toIndentedString(numberInfoList)).append("\n");
    sb.append("    repeatingCount: ").append(toIndentedString(repeatingCount)).append("\n");
    sb.append("    sendTime: ").append(toIndentedString(sendTime)).append("\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    voiceContent: ").append(toIndentedString(voiceContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
