/*
 * vs20260714
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.vs20260714.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.vs20260714.model.DataForCreateVoiceTaskOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateVoiceTaskResponse
 */



public class CreateVoiceTaskResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("Data")
  private DataForCreateVoiceTaskOutput data = null;

  @SerializedName("ErrorMessage")
  private String errorMessage = null;

  @SerializedName("Result")
  private String result = null;

  public CreateVoiceTaskResponse data(DataForCreateVoiceTaskOutput data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Valid
  @Schema(description = "")
  public DataForCreateVoiceTaskOutput getData() {
    return data;
  }

  public void setData(DataForCreateVoiceTaskOutput data) {
    this.data = data;
  }

  public CreateVoiceTaskResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @Schema(description = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public CreateVoiceTaskResponse result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVoiceTaskResponse createVoiceTaskResponse = (CreateVoiceTaskResponse) o;
    return Objects.equals(this.data, createVoiceTaskResponse.data) &&
        Objects.equals(this.errorMessage, createVoiceTaskResponse.errorMessage) &&
        Objects.equals(this.result, createVoiceTaskResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errorMessage, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVoiceTaskResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
