/*
 * cpaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.cpaas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ElementStyleForGetTemplateV2Output
 */



public class ElementStyleForGetTemplateV2Output {
  @SerializedName("ElementType")
  private String elementType = null;

  @SerializedName("ExpiresTime")
  private Integer expiresTime = null;

  @SerializedName("HasExpires")
  private Boolean hasExpires = null;

  @SerializedName("HasSecurity")
  private Boolean hasSecurity = null;

  @SerializedName("RealContent")
  private String realContent = null;

  @SerializedName("ResourceCode")
  private String resourceCode = null;

  @SerializedName("ResourceName")
  private String resourceName = null;

  @SerializedName("ResourceUrl")
  private String resourceUrl = null;

  public ElementStyleForGetTemplateV2Output elementType(String elementType) {
    this.elementType = elementType;
    return this;
  }

   /**
   * Get elementType
   * @return elementType
  **/
  @Schema(description = "")
  public String getElementType() {
    return elementType;
  }

  public void setElementType(String elementType) {
    this.elementType = elementType;
  }

  public ElementStyleForGetTemplateV2Output expiresTime(Integer expiresTime) {
    this.expiresTime = expiresTime;
    return this;
  }

   /**
   * Get expiresTime
   * @return expiresTime
  **/
  @Schema(description = "")
  public Integer getExpiresTime() {
    return expiresTime;
  }

  public void setExpiresTime(Integer expiresTime) {
    this.expiresTime = expiresTime;
  }

  public ElementStyleForGetTemplateV2Output hasExpires(Boolean hasExpires) {
    this.hasExpires = hasExpires;
    return this;
  }

   /**
   * Get hasExpires
   * @return hasExpires
  **/
  @Schema(description = "")
  public Boolean isHasExpires() {
    return hasExpires;
  }

  public void setHasExpires(Boolean hasExpires) {
    this.hasExpires = hasExpires;
  }

  public ElementStyleForGetTemplateV2Output hasSecurity(Boolean hasSecurity) {
    this.hasSecurity = hasSecurity;
    return this;
  }

   /**
   * Get hasSecurity
   * @return hasSecurity
  **/
  @Schema(description = "")
  public Boolean isHasSecurity() {
    return hasSecurity;
  }

  public void setHasSecurity(Boolean hasSecurity) {
    this.hasSecurity = hasSecurity;
  }

  public ElementStyleForGetTemplateV2Output realContent(String realContent) {
    this.realContent = realContent;
    return this;
  }

   /**
   * Get realContent
   * @return realContent
  **/
  @Schema(description = "")
  public String getRealContent() {
    return realContent;
  }

  public void setRealContent(String realContent) {
    this.realContent = realContent;
  }

  public ElementStyleForGetTemplateV2Output resourceCode(String resourceCode) {
    this.resourceCode = resourceCode;
    return this;
  }

   /**
   * Get resourceCode
   * @return resourceCode
  **/
  @Schema(description = "")
  public String getResourceCode() {
    return resourceCode;
  }

  public void setResourceCode(String resourceCode) {
    this.resourceCode = resourceCode;
  }

  public ElementStyleForGetTemplateV2Output resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

   /**
   * Get resourceName
   * @return resourceName
  **/
  @Schema(description = "")
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }

  public ElementStyleForGetTemplateV2Output resourceUrl(String resourceUrl) {
    this.resourceUrl = resourceUrl;
    return this;
  }

   /**
   * Get resourceUrl
   * @return resourceUrl
  **/
  @Schema(description = "")
  public String getResourceUrl() {
    return resourceUrl;
  }

  public void setResourceUrl(String resourceUrl) {
    this.resourceUrl = resourceUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementStyleForGetTemplateV2Output elementStyleForGetTemplateV2Output = (ElementStyleForGetTemplateV2Output) o;
    return Objects.equals(this.elementType, elementStyleForGetTemplateV2Output.elementType) &&
        Objects.equals(this.expiresTime, elementStyleForGetTemplateV2Output.expiresTime) &&
        Objects.equals(this.hasExpires, elementStyleForGetTemplateV2Output.hasExpires) &&
        Objects.equals(this.hasSecurity, elementStyleForGetTemplateV2Output.hasSecurity) &&
        Objects.equals(this.realContent, elementStyleForGetTemplateV2Output.realContent) &&
        Objects.equals(this.resourceCode, elementStyleForGetTemplateV2Output.resourceCode) &&
        Objects.equals(this.resourceName, elementStyleForGetTemplateV2Output.resourceName) &&
        Objects.equals(this.resourceUrl, elementStyleForGetTemplateV2Output.resourceUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elementType, expiresTime, hasExpires, hasSecurity, realContent, resourceCode, resourceName, resourceUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementStyleForGetTemplateV2Output {\n");
    
    sb.append("    elementType: ").append(toIndentedString(elementType)).append("\n");
    sb.append("    expiresTime: ").append(toIndentedString(expiresTime)).append("\n");
    sb.append("    hasExpires: ").append(toIndentedString(hasExpires)).append("\n");
    sb.append("    hasSecurity: ").append(toIndentedString(hasSecurity)).append("\n");
    sb.append("    realContent: ").append(toIndentedString(realContent)).append("\n");
    sb.append("    resourceCode: ").append(toIndentedString(resourceCode)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    resourceUrl: ").append(toIndentedString(resourceUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
