/*
 * cpaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.cpaas.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.cpaas.model.PageDTOListForGetTemplateV2Output;
import com.byteplus.cpaas.model.VariablesDTOListForGetTemplateV2Output;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * TemplateListForGetTemplateV2Output
 */



public class TemplateListForGetTemplateV2Output {
  @SerializedName("CardButtonType")
  private List<String> cardButtonType = null;

  @SerializedName("CardHeaderType")
  private String cardHeaderType = null;

  @SerializedName("CarouselBody")
  private String carouselBody = null;

  @SerializedName("Format")
  private String format = null;

  @SerializedName("PageDTOList")
  private List<PageDTOListForGetTemplateV2Output> pageDTOList = null;

  @SerializedName("TemplateType")
  private String templateType = null;

  @SerializedName("VariablesDTOList")
  private List<VariablesDTOListForGetTemplateV2Output> variablesDTOList = null;

  @SerializedName("WhatsappCatagory")
  private String whatsappCatagory = null;

  public TemplateListForGetTemplateV2Output cardButtonType(List<String> cardButtonType) {
    this.cardButtonType = cardButtonType;
    return this;
  }

  public TemplateListForGetTemplateV2Output addCardButtonTypeItem(String cardButtonTypeItem) {
    if (this.cardButtonType == null) {
      this.cardButtonType = new ArrayList<String>();
    }
    this.cardButtonType.add(cardButtonTypeItem);
    return this;
  }

   /**
   * Get cardButtonType
   * @return cardButtonType
  **/
  @Schema(description = "")
  public List<String> getCardButtonType() {
    return cardButtonType;
  }

  public void setCardButtonType(List<String> cardButtonType) {
    this.cardButtonType = cardButtonType;
  }

  public TemplateListForGetTemplateV2Output cardHeaderType(String cardHeaderType) {
    this.cardHeaderType = cardHeaderType;
    return this;
  }

   /**
   * Get cardHeaderType
   * @return cardHeaderType
  **/
  @Schema(description = "")
  public String getCardHeaderType() {
    return cardHeaderType;
  }

  public void setCardHeaderType(String cardHeaderType) {
    this.cardHeaderType = cardHeaderType;
  }

  public TemplateListForGetTemplateV2Output carouselBody(String carouselBody) {
    this.carouselBody = carouselBody;
    return this;
  }

   /**
   * Get carouselBody
   * @return carouselBody
  **/
  @Schema(description = "")
  public String getCarouselBody() {
    return carouselBody;
  }

  public void setCarouselBody(String carouselBody) {
    this.carouselBody = carouselBody;
  }

  public TemplateListForGetTemplateV2Output format(String format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @Schema(description = "")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public TemplateListForGetTemplateV2Output pageDTOList(List<PageDTOListForGetTemplateV2Output> pageDTOList) {
    this.pageDTOList = pageDTOList;
    return this;
  }

  public TemplateListForGetTemplateV2Output addPageDTOListItem(PageDTOListForGetTemplateV2Output pageDTOListItem) {
    if (this.pageDTOList == null) {
      this.pageDTOList = new ArrayList<PageDTOListForGetTemplateV2Output>();
    }
    this.pageDTOList.add(pageDTOListItem);
    return this;
  }

   /**
   * Get pageDTOList
   * @return pageDTOList
  **/
  @Valid
  @Schema(description = "")
  public List<PageDTOListForGetTemplateV2Output> getPageDTOList() {
    return pageDTOList;
  }

  public void setPageDTOList(List<PageDTOListForGetTemplateV2Output> pageDTOList) {
    this.pageDTOList = pageDTOList;
  }

  public TemplateListForGetTemplateV2Output templateType(String templateType) {
    this.templateType = templateType;
    return this;
  }

   /**
   * Get templateType
   * @return templateType
  **/
  @Schema(description = "")
  public String getTemplateType() {
    return templateType;
  }

  public void setTemplateType(String templateType) {
    this.templateType = templateType;
  }

  public TemplateListForGetTemplateV2Output variablesDTOList(List<VariablesDTOListForGetTemplateV2Output> variablesDTOList) {
    this.variablesDTOList = variablesDTOList;
    return this;
  }

  public TemplateListForGetTemplateV2Output addVariablesDTOListItem(VariablesDTOListForGetTemplateV2Output variablesDTOListItem) {
    if (this.variablesDTOList == null) {
      this.variablesDTOList = new ArrayList<VariablesDTOListForGetTemplateV2Output>();
    }
    this.variablesDTOList.add(variablesDTOListItem);
    return this;
  }

   /**
   * Get variablesDTOList
   * @return variablesDTOList
  **/
  @Valid
  @Schema(description = "")
  public List<VariablesDTOListForGetTemplateV2Output> getVariablesDTOList() {
    return variablesDTOList;
  }

  public void setVariablesDTOList(List<VariablesDTOListForGetTemplateV2Output> variablesDTOList) {
    this.variablesDTOList = variablesDTOList;
  }

  public TemplateListForGetTemplateV2Output whatsappCatagory(String whatsappCatagory) {
    this.whatsappCatagory = whatsappCatagory;
    return this;
  }

   /**
   * Get whatsappCatagory
   * @return whatsappCatagory
  **/
  @Schema(description = "")
  public String getWhatsappCatagory() {
    return whatsappCatagory;
  }

  public void setWhatsappCatagory(String whatsappCatagory) {
    this.whatsappCatagory = whatsappCatagory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateListForGetTemplateV2Output templateListForGetTemplateV2Output = (TemplateListForGetTemplateV2Output) o;
    return Objects.equals(this.cardButtonType, templateListForGetTemplateV2Output.cardButtonType) &&
        Objects.equals(this.cardHeaderType, templateListForGetTemplateV2Output.cardHeaderType) &&
        Objects.equals(this.carouselBody, templateListForGetTemplateV2Output.carouselBody) &&
        Objects.equals(this.format, templateListForGetTemplateV2Output.format) &&
        Objects.equals(this.pageDTOList, templateListForGetTemplateV2Output.pageDTOList) &&
        Objects.equals(this.templateType, templateListForGetTemplateV2Output.templateType) &&
        Objects.equals(this.variablesDTOList, templateListForGetTemplateV2Output.variablesDTOList) &&
        Objects.equals(this.whatsappCatagory, templateListForGetTemplateV2Output.whatsappCatagory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardButtonType, cardHeaderType, carouselBody, format, pageDTOList, templateType, variablesDTOList, whatsappCatagory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateListForGetTemplateV2Output {\n");
    
    sb.append("    cardButtonType: ").append(toIndentedString(cardButtonType)).append("\n");
    sb.append("    cardHeaderType: ").append(toIndentedString(cardHeaderType)).append("\n");
    sb.append("    carouselBody: ").append(toIndentedString(carouselBody)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    pageDTOList: ").append(toIndentedString(pageDTOList)).append("\n");
    sb.append("    templateType: ").append(toIndentedString(templateType)).append("\n");
    sb.append("    variablesDTOList: ").append(toIndentedString(variablesDTOList)).append("\n");
    sb.append("    whatsappCatagory: ").append(toIndentedString(whatsappCatagory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
