/*
 * cr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.cr.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.cr.model.PermissionForCreateRobotAccountInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateRobotAccountRequest
 */



public class CreateRobotAccountRequest {
  @SerializedName("Description")
  private String description = null;

  @SerializedName("Duration")
  private Long duration = null;

  @SerializedName("Password")
  private String password = null;

  @SerializedName("Permissions")
  private List<PermissionForCreateRobotAccountInput> permissions = null;

  @SerializedName("Registry")
  private String registry = null;

  @SerializedName("Username")
  private String username = null;

  public CreateRobotAccountRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateRobotAccountRequest duration(Long duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getDuration() {
    return duration;
  }

  public void setDuration(Long duration) {
    this.duration = duration;
  }

  public CreateRobotAccountRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @Schema(description = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public CreateRobotAccountRequest permissions(List<PermissionForCreateRobotAccountInput> permissions) {
    this.permissions = permissions;
    return this;
  }

  public CreateRobotAccountRequest addPermissionsItem(PermissionForCreateRobotAccountInput permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<PermissionForCreateRobotAccountInput>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @Valid
  @Schema(description = "")
  public List<PermissionForCreateRobotAccountInput> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<PermissionForCreateRobotAccountInput> permissions) {
    this.permissions = permissions;
  }

  public CreateRobotAccountRequest registry(String registry) {
    this.registry = registry;
    return this;
  }

   /**
   * Get registry
   * @return registry
  **/
  @NotNull
 @Size(min=3,max=30)  @Schema(required = true, description = "")
  public String getRegistry() {
    return registry;
  }

  public void setRegistry(String registry) {
    this.registry = registry;
  }

  public CreateRobotAccountRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRobotAccountRequest createRobotAccountRequest = (CreateRobotAccountRequest) o;
    return Objects.equals(this.description, createRobotAccountRequest.description) &&
        Objects.equals(this.duration, createRobotAccountRequest.duration) &&
        Objects.equals(this.password, createRobotAccountRequest.password) &&
        Objects.equals(this.permissions, createRobotAccountRequest.permissions) &&
        Objects.equals(this.registry, createRobotAccountRequest.registry) &&
        Objects.equals(this.username, createRobotAccountRequest.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, duration, password, permissions, registry, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRobotAccountRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
