/*
 * eco_partner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ecopartner.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ModifyQuotaResponse
 */



public class ModifyQuotaResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("LastUpdatedTime")
  private String lastUpdatedTime = null;

  @SerializedName("OutstandingAmount")
  private Float outstandingAmount = null;

  @SerializedName("QuotaAllocatedAfter")
  private Float quotaAllocatedAfter = null;

  @SerializedName("QuotaAllocatedBefore")
  private Float quotaAllocatedBefore = null;

  @SerializedName("QuotaBalance")
  private Float quotaBalance = null;

  @SerializedName("QuotaUnit")
  private String quotaUnit = null;

  @SerializedName("Uid")
  private Long uid = null;

  public ModifyQuotaResponse lastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
    return this;
  }

   /**
   * Get lastUpdatedTime
   * @return lastUpdatedTime
  **/
  @Schema(description = "")
  public String getLastUpdatedTime() {
    return lastUpdatedTime;
  }

  public void setLastUpdatedTime(String lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  public ModifyQuotaResponse outstandingAmount(Float outstandingAmount) {
    this.outstandingAmount = outstandingAmount;
    return this;
  }

   /**
   * Get outstandingAmount
   * @return outstandingAmount
  **/
  @Schema(description = "")
  public Float getOutstandingAmount() {
    return outstandingAmount;
  }

  public void setOutstandingAmount(Float outstandingAmount) {
    this.outstandingAmount = outstandingAmount;
  }

  public ModifyQuotaResponse quotaAllocatedAfter(Float quotaAllocatedAfter) {
    this.quotaAllocatedAfter = quotaAllocatedAfter;
    return this;
  }

   /**
   * Get quotaAllocatedAfter
   * @return quotaAllocatedAfter
  **/
  @Schema(description = "")
  public Float getQuotaAllocatedAfter() {
    return quotaAllocatedAfter;
  }

  public void setQuotaAllocatedAfter(Float quotaAllocatedAfter) {
    this.quotaAllocatedAfter = quotaAllocatedAfter;
  }

  public ModifyQuotaResponse quotaAllocatedBefore(Float quotaAllocatedBefore) {
    this.quotaAllocatedBefore = quotaAllocatedBefore;
    return this;
  }

   /**
   * Get quotaAllocatedBefore
   * @return quotaAllocatedBefore
  **/
  @Schema(description = "")
  public Float getQuotaAllocatedBefore() {
    return quotaAllocatedBefore;
  }

  public void setQuotaAllocatedBefore(Float quotaAllocatedBefore) {
    this.quotaAllocatedBefore = quotaAllocatedBefore;
  }

  public ModifyQuotaResponse quotaBalance(Float quotaBalance) {
    this.quotaBalance = quotaBalance;
    return this;
  }

   /**
   * Get quotaBalance
   * @return quotaBalance
  **/
  @Schema(description = "")
  public Float getQuotaBalance() {
    return quotaBalance;
  }

  public void setQuotaBalance(Float quotaBalance) {
    this.quotaBalance = quotaBalance;
  }

  public ModifyQuotaResponse quotaUnit(String quotaUnit) {
    this.quotaUnit = quotaUnit;
    return this;
  }

   /**
   * Get quotaUnit
   * @return quotaUnit
  **/
  @Schema(description = "")
  public String getQuotaUnit() {
    return quotaUnit;
  }

  public void setQuotaUnit(String quotaUnit) {
    this.quotaUnit = quotaUnit;
  }

  public ModifyQuotaResponse uid(Long uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(description = "")
  public Long getUid() {
    return uid;
  }

  public void setUid(Long uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyQuotaResponse modifyQuotaResponse = (ModifyQuotaResponse) o;
    return Objects.equals(this.lastUpdatedTime, modifyQuotaResponse.lastUpdatedTime) &&
        Objects.equals(this.outstandingAmount, modifyQuotaResponse.outstandingAmount) &&
        Objects.equals(this.quotaAllocatedAfter, modifyQuotaResponse.quotaAllocatedAfter) &&
        Objects.equals(this.quotaAllocatedBefore, modifyQuotaResponse.quotaAllocatedBefore) &&
        Objects.equals(this.quotaBalance, modifyQuotaResponse.quotaBalance) &&
        Objects.equals(this.quotaUnit, modifyQuotaResponse.quotaUnit) &&
        Objects.equals(this.uid, modifyQuotaResponse.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastUpdatedTime, outstandingAmount, quotaAllocatedAfter, quotaAllocatedBefore, quotaBalance, quotaUnit, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyQuotaResponse {\n");
    
    sb.append("    lastUpdatedTime: ").append(toIndentedString(lastUpdatedTime)).append("\n");
    sb.append("    outstandingAmount: ").append(toIndentedString(outstandingAmount)).append("\n");
    sb.append("    quotaAllocatedAfter: ").append(toIndentedString(quotaAllocatedAfter)).append("\n");
    sb.append("    quotaAllocatedBefore: ").append(toIndentedString(quotaAllocatedBefore)).append("\n");
    sb.append("    quotaBalance: ").append(toIndentedString(quotaBalance)).append("\n");
    sb.append("    quotaUnit: ").append(toIndentedString(quotaUnit)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
