/*
 * eco_partner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ecopartner.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ModifyQuotaRequest
 */



public class ModifyQuotaRequest {
  @SerializedName("QuotaAmount")
  private Float quotaAmount = null;

  @SerializedName("Remarks")
  private String remarks = null;

  @SerializedName("Uid")
  private Long uid = null;

  public ModifyQuotaRequest quotaAmount(Float quotaAmount) {
    this.quotaAmount = quotaAmount;
    return this;
  }

   /**
   * Get quotaAmount
   * @return quotaAmount
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Float getQuotaAmount() {
    return quotaAmount;
  }

  public void setQuotaAmount(Float quotaAmount) {
    this.quotaAmount = quotaAmount;
  }

  public ModifyQuotaRequest remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * Get remarks
   * @return remarks
  **/
 @Size(max=512)  @Schema(description = "")
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public ModifyQuotaRequest uid(Long uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getUid() {
    return uid;
  }

  public void setUid(Long uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyQuotaRequest modifyQuotaRequest = (ModifyQuotaRequest) o;
    return Objects.equals(this.quotaAmount, modifyQuotaRequest.quotaAmount) &&
        Objects.equals(this.remarks, modifyQuotaRequest.remarks) &&
        Objects.equals(this.uid, modifyQuotaRequest.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quotaAmount, remarks, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyQuotaRequest {\n");
    
    sb.append("    quotaAmount: ").append(toIndentedString(quotaAmount)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
