/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CheckProductUrlResponse
 */



public class CheckProductUrlResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("UrlInfo")
  private String urlInfo = null;

  public CheckProductUrlResponse urlInfo(String urlInfo) {
    this.urlInfo = urlInfo;
    return this;
  }

   /**
   * Get urlInfo
   * @return urlInfo
  **/
  @Schema(description = "")
  public String getUrlInfo() {
    return urlInfo;
  }

  public void setUrlInfo(String urlInfo) {
    this.urlInfo = urlInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckProductUrlResponse checkProductUrlResponse = (CheckProductUrlResponse) o;
    return Objects.equals(this.urlInfo, checkProductUrlResponse.urlInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(urlInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckProductUrlResponse {\n");
    
    sb.append("    urlInfo: ").append(toIndentedString(urlInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
