/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ClearAdVariationsProjectRequest
 */



public class ClearAdVariationsProjectRequest {
  @SerializedName("CompositionId")
  private String compositionId = null;

  @SerializedName("ProjectId")
  private String projectId = null;

  public ClearAdVariationsProjectRequest compositionId(String compositionId) {
    this.compositionId = compositionId;
    return this;
  }

   /**
   * Get compositionId
   * @return compositionId
  **/
  @Schema(description = "")
  public String getCompositionId() {
    return compositionId;
  }

  public void setCompositionId(String compositionId) {
    this.compositionId = compositionId;
  }

  public ClearAdVariationsProjectRequest projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClearAdVariationsProjectRequest clearAdVariationsProjectRequest = (ClearAdVariationsProjectRequest) o;
    return Objects.equals(this.compositionId, clearAdVariationsProjectRequest.compositionId) &&
        Objects.equals(this.projectId, clearAdVariationsProjectRequest.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compositionId, projectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClearAdVariationsProjectRequest {\n");
    
    sb.append("    compositionId: ").append(toIndentedString(compositionId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
