/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateMediaRequest
 */



public class CreateMediaRequest {
  @SerializedName("AspectRatio")
  private String aspectRatio = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("FolderId")
  private Long folderId = null;

  @SerializedName("MediaExtension")
  private String mediaExtension = null;

  @SerializedName("NotSaveToAsset")
  private Boolean notSaveToAsset = null;

  @SerializedName("ResourceItem")
  private String resourceItem = null;

  @SerializedName("ResourceType")
  private String resourceType = null;

  @SerializedName("Tags")
  private List<String> tags = null;

  @SerializedName("TeamSpaceId")
  private Long teamSpaceId = null;

  @SerializedName("Title")
  private String title = null;

  public CreateMediaRequest aspectRatio(String aspectRatio) {
    this.aspectRatio = aspectRatio;
    return this;
  }

   /**
   * Get aspectRatio
   * @return aspectRatio
  **/
  @Schema(description = "")
  public String getAspectRatio() {
    return aspectRatio;
  }

  public void setAspectRatio(String aspectRatio) {
    this.aspectRatio = aspectRatio;
  }

  public CreateMediaRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateMediaRequest folderId(Long folderId) {
    this.folderId = folderId;
    return this;
  }

   /**
   * Get folderId
   * @return folderId
  **/
  @Schema(description = "")
  public Long getFolderId() {
    return folderId;
  }

  public void setFolderId(Long folderId) {
    this.folderId = folderId;
  }

  public CreateMediaRequest mediaExtension(String mediaExtension) {
    this.mediaExtension = mediaExtension;
    return this;
  }

   /**
   * Get mediaExtension
   * @return mediaExtension
  **/
  @Schema(description = "")
  public String getMediaExtension() {
    return mediaExtension;
  }

  public void setMediaExtension(String mediaExtension) {
    this.mediaExtension = mediaExtension;
  }

  public CreateMediaRequest notSaveToAsset(Boolean notSaveToAsset) {
    this.notSaveToAsset = notSaveToAsset;
    return this;
  }

   /**
   * Get notSaveToAsset
   * @return notSaveToAsset
  **/
  @Schema(description = "")
  public Boolean isNotSaveToAsset() {
    return notSaveToAsset;
  }

  public void setNotSaveToAsset(Boolean notSaveToAsset) {
    this.notSaveToAsset = notSaveToAsset;
  }

  public CreateMediaRequest resourceItem(String resourceItem) {
    this.resourceItem = resourceItem;
    return this;
  }

   /**
   * Get resourceItem
   * @return resourceItem
  **/
  @Schema(description = "")
  public String getResourceItem() {
    return resourceItem;
  }

  public void setResourceItem(String resourceItem) {
    this.resourceItem = resourceItem;
  }

  public CreateMediaRequest resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @Schema(description = "")
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public CreateMediaRequest tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CreateMediaRequest addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @Schema(description = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public CreateMediaRequest teamSpaceId(Long teamSpaceId) {
    this.teamSpaceId = teamSpaceId;
    return this;
  }

   /**
   * Get teamSpaceId
   * @return teamSpaceId
  **/
  @Schema(description = "")
  public Long getTeamSpaceId() {
    return teamSpaceId;
  }

  public void setTeamSpaceId(Long teamSpaceId) {
    this.teamSpaceId = teamSpaceId;
  }

  public CreateMediaRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMediaRequest createMediaRequest = (CreateMediaRequest) o;
    return Objects.equals(this.aspectRatio, createMediaRequest.aspectRatio) &&
        Objects.equals(this.description, createMediaRequest.description) &&
        Objects.equals(this.folderId, createMediaRequest.folderId) &&
        Objects.equals(this.mediaExtension, createMediaRequest.mediaExtension) &&
        Objects.equals(this.notSaveToAsset, createMediaRequest.notSaveToAsset) &&
        Objects.equals(this.resourceItem, createMediaRequest.resourceItem) &&
        Objects.equals(this.resourceType, createMediaRequest.resourceType) &&
        Objects.equals(this.tags, createMediaRequest.tags) &&
        Objects.equals(this.teamSpaceId, createMediaRequest.teamSpaceId) &&
        Objects.equals(this.title, createMediaRequest.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aspectRatio, description, folderId, mediaExtension, notSaveToAsset, resourceItem, resourceType, tags, teamSpaceId, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMediaRequest {\n");
    
    sb.append("    aspectRatio: ").append(toIndentedString(aspectRatio)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    folderId: ").append(toIndentedString(folderId)).append("\n");
    sb.append("    mediaExtension: ").append(toIndentedString(mediaExtension)).append("\n");
    sb.append("    notSaveToAsset: ").append(toIndentedString(notSaveToAsset)).append("\n");
    sb.append("    resourceItem: ").append(toIndentedString(resourceItem)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    teamSpaceId: ").append(toIndentedString(teamSpaceId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
