/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateProjectResponse
 */



public class CreateProjectResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("Blocks")
  private List<String> blocks = null;

  @SerializedName("CompositionId")
  private String compositionId = null;

  @SerializedName("ProjectId")
  private String projectId = null;

  @SerializedName("VideoType")
  private String videoType = null;

  public CreateProjectResponse blocks(List<String> blocks) {
    this.blocks = blocks;
    return this;
  }

  public CreateProjectResponse addBlocksItem(String blocksItem) {
    if (this.blocks == null) {
      this.blocks = new ArrayList<String>();
    }
    this.blocks.add(blocksItem);
    return this;
  }

   /**
   * Get blocks
   * @return blocks
  **/
  @Schema(description = "")
  public List<String> getBlocks() {
    return blocks;
  }

  public void setBlocks(List<String> blocks) {
    this.blocks = blocks;
  }

  public CreateProjectResponse compositionId(String compositionId) {
    this.compositionId = compositionId;
    return this;
  }

   /**
   * Get compositionId
   * @return compositionId
  **/
  @Schema(description = "")
  public String getCompositionId() {
    return compositionId;
  }

  public void setCompositionId(String compositionId) {
    this.compositionId = compositionId;
  }

  public CreateProjectResponse projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(description = "")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public CreateProjectResponse videoType(String videoType) {
    this.videoType = videoType;
    return this;
  }

   /**
   * Get videoType
   * @return videoType
  **/
  @Schema(description = "")
  public String getVideoType() {
    return videoType;
  }

  public void setVideoType(String videoType) {
    this.videoType = videoType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProjectResponse createProjectResponse = (CreateProjectResponse) o;
    return Objects.equals(this.blocks, createProjectResponse.blocks) &&
        Objects.equals(this.compositionId, createProjectResponse.compositionId) &&
        Objects.equals(this.projectId, createProjectResponse.projectId) &&
        Objects.equals(this.videoType, createProjectResponse.videoType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocks, compositionId, projectId, videoType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProjectResponse {\n");
    
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    compositionId: ").append(toIndentedString(compositionId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    videoType: ").append(toIndentedString(videoType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
