/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateItemRequest
 */



public class CreateItemRequest {
  @SerializedName("BuyChannel")
  private String buyChannel = null;

  @SerializedName("ComboStartDt")
  private Integer comboStartDt = null;

  @SerializedName("EnterFrom")
  private String enterFrom = null;

  @SerializedName("Id")
  private String id = null;

  @SerializedName("IsInvitedByPartner")
  private Integer isInvitedByPartner = null;

  public CreateItemRequest buyChannel(String buyChannel) {
    this.buyChannel = buyChannel;
    return this;
  }

   /**
   * Get buyChannel
   * @return buyChannel
  **/
  @Schema(description = "")
  public String getBuyChannel() {
    return buyChannel;
  }

  public void setBuyChannel(String buyChannel) {
    this.buyChannel = buyChannel;
  }

  public CreateItemRequest comboStartDt(Integer comboStartDt) {
    this.comboStartDt = comboStartDt;
    return this;
  }

   /**
   * Get comboStartDt
   * @return comboStartDt
  **/
  @Schema(description = "")
  public Integer getComboStartDt() {
    return comboStartDt;
  }

  public void setComboStartDt(Integer comboStartDt) {
    this.comboStartDt = comboStartDt;
  }

  public CreateItemRequest enterFrom(String enterFrom) {
    this.enterFrom = enterFrom;
    return this;
  }

   /**
   * Get enterFrom
   * @return enterFrom
  **/
  @Schema(description = "")
  public String getEnterFrom() {
    return enterFrom;
  }

  public void setEnterFrom(String enterFrom) {
    this.enterFrom = enterFrom;
  }

  public CreateItemRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CreateItemRequest isInvitedByPartner(Integer isInvitedByPartner) {
    this.isInvitedByPartner = isInvitedByPartner;
    return this;
  }

   /**
   * Get isInvitedByPartner
   * @return isInvitedByPartner
  **/
  @Schema(description = "")
  public Integer getIsInvitedByPartner() {
    return isInvitedByPartner;
  }

  public void setIsInvitedByPartner(Integer isInvitedByPartner) {
    this.isInvitedByPartner = isInvitedByPartner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateItemRequest createItemRequest = (CreateItemRequest) o;
    return Objects.equals(this.buyChannel, createItemRequest.buyChannel) &&
        Objects.equals(this.comboStartDt, createItemRequest.comboStartDt) &&
        Objects.equals(this.enterFrom, createItemRequest.enterFrom) &&
        Objects.equals(this.id, createItemRequest.id) &&
        Objects.equals(this.isInvitedByPartner, createItemRequest.isInvitedByPartner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyChannel, comboStartDt, enterFrom, id, isInvitedByPartner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateItemRequest {\n");
    
    sb.append("    buyChannel: ").append(toIndentedString(buyChannel)).append("\n");
    sb.append("    comboStartDt: ").append(toIndentedString(comboStartDt)).append("\n");
    sb.append("    enterFrom: ").append(toIndentedString(enterFrom)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isInvitedByPartner: ").append(toIndentedString(isInvitedByPartner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
