/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ExportEditorVideoRequest
 */



public class ExportEditorVideoRequest {
  @SerializedName("Crf")
  private Integer crf = null;

  @SerializedName("DraftId")
  private String draftId = null;

  @SerializedName("Duration")
  private Integer duration = null;

  @SerializedName("Fps")
  private Integer fps = null;

  @SerializedName("Height")
  private Integer height = null;

  @SerializedName("Watermark")
  private Boolean watermark = null;

  @SerializedName("Width")
  private Integer width = null;

  public ExportEditorVideoRequest crf(Integer crf) {
    this.crf = crf;
    return this;
  }

   /**
   * Get crf
   * @return crf
  **/
  @Schema(description = "")
  public Integer getCrf() {
    return crf;
  }

  public void setCrf(Integer crf) {
    this.crf = crf;
  }

  public ExportEditorVideoRequest draftId(String draftId) {
    this.draftId = draftId;
    return this;
  }

   /**
   * Get draftId
   * @return draftId
  **/
  @Schema(description = "")
  public String getDraftId() {
    return draftId;
  }

  public void setDraftId(String draftId) {
    this.draftId = draftId;
  }

  public ExportEditorVideoRequest duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public ExportEditorVideoRequest fps(Integer fps) {
    this.fps = fps;
    return this;
  }

   /**
   * Get fps
   * @return fps
  **/
  @Schema(description = "")
  public Integer getFps() {
    return fps;
  }

  public void setFps(Integer fps) {
    this.fps = fps;
  }

  public ExportEditorVideoRequest height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @Schema(description = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public ExportEditorVideoRequest watermark(Boolean watermark) {
    this.watermark = watermark;
    return this;
  }

   /**
   * Get watermark
   * @return watermark
  **/
  @Schema(description = "")
  public Boolean isWatermark() {
    return watermark;
  }

  public void setWatermark(Boolean watermark) {
    this.watermark = watermark;
  }

  public ExportEditorVideoRequest width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @Schema(description = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportEditorVideoRequest exportEditorVideoRequest = (ExportEditorVideoRequest) o;
    return Objects.equals(this.crf, exportEditorVideoRequest.crf) &&
        Objects.equals(this.draftId, exportEditorVideoRequest.draftId) &&
        Objects.equals(this.duration, exportEditorVideoRequest.duration) &&
        Objects.equals(this.fps, exportEditorVideoRequest.fps) &&
        Objects.equals(this.height, exportEditorVideoRequest.height) &&
        Objects.equals(this.watermark, exportEditorVideoRequest.watermark) &&
        Objects.equals(this.width, exportEditorVideoRequest.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crf, draftId, duration, fps, height, watermark, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportEditorVideoRequest {\n");
    
    sb.append("    crf: ").append(toIndentedString(crf)).append("\n");
    sb.append("    draftId: ").append(toIndentedString(draftId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    fps: ").append(toIndentedString(fps)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    watermark: ").append(toIndentedString(watermark)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
