/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GenProductStoryboardOutlineResponse
 */



public class GenProductStoryboardOutlineResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("TaskId")
  private String taskId = null;

  @SerializedName("UpdateBlocks")
  private List<String> updateBlocks = null;

  public GenProductStoryboardOutlineResponse taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @Schema(description = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public GenProductStoryboardOutlineResponse updateBlocks(List<String> updateBlocks) {
    this.updateBlocks = updateBlocks;
    return this;
  }

  public GenProductStoryboardOutlineResponse addUpdateBlocksItem(String updateBlocksItem) {
    if (this.updateBlocks == null) {
      this.updateBlocks = new ArrayList<String>();
    }
    this.updateBlocks.add(updateBlocksItem);
    return this;
  }

   /**
   * Get updateBlocks
   * @return updateBlocks
  **/
  @Schema(description = "")
  public List<String> getUpdateBlocks() {
    return updateBlocks;
  }

  public void setUpdateBlocks(List<String> updateBlocks) {
    this.updateBlocks = updateBlocks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenProductStoryboardOutlineResponse genProductStoryboardOutlineResponse = (GenProductStoryboardOutlineResponse) o;
    return Objects.equals(this.taskId, genProductStoryboardOutlineResponse.taskId) &&
        Objects.equals(this.updateBlocks, genProductStoryboardOutlineResponse.updateBlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, updateBlocks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenProductStoryboardOutlineResponse {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    updateBlocks: ").append(toIndentedString(updateBlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
