/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GenProductStoryboardVideoRequest
 */



public class GenProductStoryboardVideoRequest {
  @SerializedName("BlockId")
  private String blockId = null;

  @SerializedName("Lang")
  private String lang = null;

  @SerializedName("SelectedId")
  private String selectedId = null;

  public GenProductStoryboardVideoRequest blockId(String blockId) {
    this.blockId = blockId;
    return this;
  }

   /**
   * Get blockId
   * @return blockId
  **/
  @Schema(description = "")
  public String getBlockId() {
    return blockId;
  }

  public void setBlockId(String blockId) {
    this.blockId = blockId;
  }

  public GenProductStoryboardVideoRequest lang(String lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @Schema(description = "")
  public String getLang() {
    return lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }

  public GenProductStoryboardVideoRequest selectedId(String selectedId) {
    this.selectedId = selectedId;
    return this;
  }

   /**
   * Get selectedId
   * @return selectedId
  **/
  @Schema(description = "")
  public String getSelectedId() {
    return selectedId;
  }

  public void setSelectedId(String selectedId) {
    this.selectedId = selectedId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenProductStoryboardVideoRequest genProductStoryboardVideoRequest = (GenProductStoryboardVideoRequest) o;
    return Objects.equals(this.blockId, genProductStoryboardVideoRequest.blockId) &&
        Objects.equals(this.lang, genProductStoryboardVideoRequest.lang) &&
        Objects.equals(this.selectedId, genProductStoryboardVideoRequest.selectedId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockId, lang, selectedId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenProductStoryboardVideoRequest {\n");
    
    sb.append("    blockId: ").append(toIndentedString(blockId)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    selectedId: ").append(toIndentedString(selectedId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
