/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GenPicByPromptRequest
 */



public class GenPicByPromptRequest {
  @SerializedName("CompositionId")
  private String compositionId = null;

  @SerializedName("Lang")
  private String lang = null;

  @SerializedName("SceneId")
  private String sceneId = null;

  public GenPicByPromptRequest compositionId(String compositionId) {
    this.compositionId = compositionId;
    return this;
  }

   /**
   * Get compositionId
   * @return compositionId
  **/
  @Schema(description = "")
  public String getCompositionId() {
    return compositionId;
  }

  public void setCompositionId(String compositionId) {
    this.compositionId = compositionId;
  }

  public GenPicByPromptRequest lang(String lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @Schema(description = "")
  public String getLang() {
    return lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }

  public GenPicByPromptRequest sceneId(String sceneId) {
    this.sceneId = sceneId;
    return this;
  }

   /**
   * Get sceneId
   * @return sceneId
  **/
  @Schema(description = "")
  public String getSceneId() {
    return sceneId;
  }

  public void setSceneId(String sceneId) {
    this.sceneId = sceneId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenPicByPromptRequest genPicByPromptRequest = (GenPicByPromptRequest) o;
    return Objects.equals(this.compositionId, genPicByPromptRequest.compositionId) &&
        Objects.equals(this.lang, genPicByPromptRequest.lang) &&
        Objects.equals(this.sceneId, genPicByPromptRequest.sceneId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compositionId, lang, sceneId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenPicByPromptRequest {\n");
    
    sb.append("    compositionId: ").append(toIndentedString(compositionId)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    sceneId: ").append(toIndentedString(sceneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
