/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GenTemplateVideoResponse
 */



public class GenTemplateVideoResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("NewBlocks")
  private List<String> newBlocks = null;

  @SerializedName("TaskId")
  private String taskId = null;

  public GenTemplateVideoResponse newBlocks(List<String> newBlocks) {
    this.newBlocks = newBlocks;
    return this;
  }

  public GenTemplateVideoResponse addNewBlocksItem(String newBlocksItem) {
    if (this.newBlocks == null) {
      this.newBlocks = new ArrayList<String>();
    }
    this.newBlocks.add(newBlocksItem);
    return this;
  }

   /**
   * Get newBlocks
   * @return newBlocks
  **/
  @Schema(description = "")
  public List<String> getNewBlocks() {
    return newBlocks;
  }

  public void setNewBlocks(List<String> newBlocks) {
    this.newBlocks = newBlocks;
  }

  public GenTemplateVideoResponse taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @Schema(description = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenTemplateVideoResponse genTemplateVideoResponse = (GenTemplateVideoResponse) o;
    return Objects.equals(this.newBlocks, genTemplateVideoResponse.newBlocks) &&
        Objects.equals(this.taskId, genTemplateVideoResponse.taskId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newBlocks, taskId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenTemplateVideoResponse {\n");
    
    sb.append("    newBlocks: ").append(toIndentedString(newBlocks)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
