/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetAvatarRequest
 */



public class GetAvatarRequest {
  @SerializedName("AvatarIds")
  private List<String> avatarIds = null;

  public GetAvatarRequest avatarIds(List<String> avatarIds) {
    this.avatarIds = avatarIds;
    return this;
  }

  public GetAvatarRequest addAvatarIdsItem(String avatarIdsItem) {
    if (this.avatarIds == null) {
      this.avatarIds = new ArrayList<String>();
    }
    this.avatarIds.add(avatarIdsItem);
    return this;
  }

   /**
   * Get avatarIds
   * @return avatarIds
  **/
  @Schema(description = "")
  public List<String> getAvatarIds() {
    return avatarIds;
  }

  public void setAvatarIds(List<String> avatarIds) {
    this.avatarIds = avatarIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvatarRequest getAvatarRequest = (GetAvatarRequest) o;
    return Objects.equals(this.avatarIds, getAvatarRequest.avatarIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatarIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvatarRequest {\n");
    
    sb.append("    avatarIds: ").append(toIndentedString(avatarIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
