/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetAiTemplateTemplateInfoResponse
 */



public class GetAiTemplateTemplateInfoResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("TemplateInfos")
  private List<String> templateInfos = null;

  public GetAiTemplateTemplateInfoResponse templateInfos(List<String> templateInfos) {
    this.templateInfos = templateInfos;
    return this;
  }

  public GetAiTemplateTemplateInfoResponse addTemplateInfosItem(String templateInfosItem) {
    if (this.templateInfos == null) {
      this.templateInfos = new ArrayList<String>();
    }
    this.templateInfos.add(templateInfosItem);
    return this;
  }

   /**
   * Get templateInfos
   * @return templateInfos
  **/
  @Schema(description = "")
  public List<String> getTemplateInfos() {
    return templateInfos;
  }

  public void setTemplateInfos(List<String> templateInfos) {
    this.templateInfos = templateInfos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAiTemplateTemplateInfoResponse getAiTemplateTemplateInfoResponse = (GetAiTemplateTemplateInfoResponse) o;
    return Objects.equals(this.templateInfos, getAiTemplateTemplateInfoResponse.templateInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateInfos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAiTemplateTemplateInfoResponse {\n");
    
    sb.append("    templateInfos: ").append(toIndentedString(templateInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
