/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetComboBalanceResponse
 */



public class GetComboBalanceResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("BalanceItems")
  private List<String> balanceItems = null;

  @SerializedName("ComboWithBalanceItems")
  private List<String> comboWithBalanceItems = null;

  public GetComboBalanceResponse balanceItems(List<String> balanceItems) {
    this.balanceItems = balanceItems;
    return this;
  }

  public GetComboBalanceResponse addBalanceItemsItem(String balanceItemsItem) {
    if (this.balanceItems == null) {
      this.balanceItems = new ArrayList<String>();
    }
    this.balanceItems.add(balanceItemsItem);
    return this;
  }

   /**
   * Get balanceItems
   * @return balanceItems
  **/
  @Schema(description = "")
  public List<String> getBalanceItems() {
    return balanceItems;
  }

  public void setBalanceItems(List<String> balanceItems) {
    this.balanceItems = balanceItems;
  }

  public GetComboBalanceResponse comboWithBalanceItems(List<String> comboWithBalanceItems) {
    this.comboWithBalanceItems = comboWithBalanceItems;
    return this;
  }

  public GetComboBalanceResponse addComboWithBalanceItemsItem(String comboWithBalanceItemsItem) {
    if (this.comboWithBalanceItems == null) {
      this.comboWithBalanceItems = new ArrayList<String>();
    }
    this.comboWithBalanceItems.add(comboWithBalanceItemsItem);
    return this;
  }

   /**
   * Get comboWithBalanceItems
   * @return comboWithBalanceItems
  **/
  @Schema(description = "")
  public List<String> getComboWithBalanceItems() {
    return comboWithBalanceItems;
  }

  public void setComboWithBalanceItems(List<String> comboWithBalanceItems) {
    this.comboWithBalanceItems = comboWithBalanceItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetComboBalanceResponse getComboBalanceResponse = (GetComboBalanceResponse) o;
    return Objects.equals(this.balanceItems, getComboBalanceResponse.balanceItems) &&
        Objects.equals(this.comboWithBalanceItems, getComboBalanceResponse.comboWithBalanceItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balanceItems, comboWithBalanceItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetComboBalanceResponse {\n");
    
    sb.append("    balanceItems: ").append(toIndentedString(balanceItems)).append("\n");
    sb.append("    comboWithBalanceItems: ").append(toIndentedString(comboWithBalanceItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
