/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetDraftRequest
 */



public class GetDraftRequest {
  @SerializedName("DraftIds")
  private List<Long> draftIds = null;

  public GetDraftRequest draftIds(List<Long> draftIds) {
    this.draftIds = draftIds;
    return this;
  }

  public GetDraftRequest addDraftIdsItem(Long draftIdsItem) {
    if (this.draftIds == null) {
      this.draftIds = new ArrayList<Long>();
    }
    this.draftIds.add(draftIdsItem);
    return this;
  }

   /**
   * Get draftIds
   * @return draftIds
  **/
  @Schema(description = "")
  public List<Long> getDraftIds() {
    return draftIds;
  }

  public void setDraftIds(List<Long> draftIds) {
    this.draftIds = draftIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDraftRequest getDraftRequest = (GetDraftRequest) o;
    return Objects.equals(this.draftIds, getDraftRequest.draftIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(draftIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDraftRequest {\n");
    
    sb.append("    draftIds: ").append(toIndentedString(draftIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
