/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetFilmDetailRequest
 */



public class GetFilmDetailRequest {
  @SerializedName("FilmIds")
  private List<String> filmIds = null;

  @SerializedName("NeedPubPlatformInfo")
  private Boolean needPubPlatformInfo = null;

  @SerializedName("UserDefinedCategoryType")
  private Integer userDefinedCategoryType = null;

  public GetFilmDetailRequest filmIds(List<String> filmIds) {
    this.filmIds = filmIds;
    return this;
  }

  public GetFilmDetailRequest addFilmIdsItem(String filmIdsItem) {
    if (this.filmIds == null) {
      this.filmIds = new ArrayList<String>();
    }
    this.filmIds.add(filmIdsItem);
    return this;
  }

   /**
   * Get filmIds
   * @return filmIds
  **/
  @Schema(description = "")
  public List<String> getFilmIds() {
    return filmIds;
  }

  public void setFilmIds(List<String> filmIds) {
    this.filmIds = filmIds;
  }

  public GetFilmDetailRequest needPubPlatformInfo(Boolean needPubPlatformInfo) {
    this.needPubPlatformInfo = needPubPlatformInfo;
    return this;
  }

   /**
   * Get needPubPlatformInfo
   * @return needPubPlatformInfo
  **/
  @Schema(description = "")
  public Boolean isNeedPubPlatformInfo() {
    return needPubPlatformInfo;
  }

  public void setNeedPubPlatformInfo(Boolean needPubPlatformInfo) {
    this.needPubPlatformInfo = needPubPlatformInfo;
  }

  public GetFilmDetailRequest userDefinedCategoryType(Integer userDefinedCategoryType) {
    this.userDefinedCategoryType = userDefinedCategoryType;
    return this;
  }

   /**
   * Get userDefinedCategoryType
   * @return userDefinedCategoryType
  **/
  @Schema(description = "")
  public Integer getUserDefinedCategoryType() {
    return userDefinedCategoryType;
  }

  public void setUserDefinedCategoryType(Integer userDefinedCategoryType) {
    this.userDefinedCategoryType = userDefinedCategoryType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFilmDetailRequest getFilmDetailRequest = (GetFilmDetailRequest) o;
    return Objects.equals(this.filmIds, getFilmDetailRequest.filmIds) &&
        Objects.equals(this.needPubPlatformInfo, getFilmDetailRequest.needPubPlatformInfo) &&
        Objects.equals(this.userDefinedCategoryType, getFilmDetailRequest.userDefinedCategoryType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filmIds, needPubPlatformInfo, userDefinedCategoryType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFilmDetailRequest {\n");
    
    sb.append("    filmIds: ").append(toIndentedString(filmIds)).append("\n");
    sb.append("    needPubPlatformInfo: ").append(toIndentedString(needPubPlatformInfo)).append("\n");
    sb.append("    userDefinedCategoryType: ").append(toIndentedString(userDefinedCategoryType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
