/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetHomeBootstrap2Response
 */



public class GetHomeBootstrap2Response extends com.byteplus.model.AbstractResponse {
  @SerializedName("ComboStatus")
  private String comboStatus = null;

  @SerializedName("HasInstance")
  private Boolean hasInstance = null;

  @SerializedName("NotifyMessage")
  private String notifyMessage = null;

  @SerializedName("Options")
  private String options = null;

  @SerializedName("User")
  private String user = null;

  @SerializedName("WatermarkNotified")
  private Boolean watermarkNotified = null;

  public GetHomeBootstrap2Response comboStatus(String comboStatus) {
    this.comboStatus = comboStatus;
    return this;
  }

   /**
   * Get comboStatus
   * @return comboStatus
  **/
  @Schema(description = "")
  public String getComboStatus() {
    return comboStatus;
  }

  public void setComboStatus(String comboStatus) {
    this.comboStatus = comboStatus;
  }

  public GetHomeBootstrap2Response hasInstance(Boolean hasInstance) {
    this.hasInstance = hasInstance;
    return this;
  }

   /**
   * Get hasInstance
   * @return hasInstance
  **/
  @Schema(description = "")
  public Boolean isHasInstance() {
    return hasInstance;
  }

  public void setHasInstance(Boolean hasInstance) {
    this.hasInstance = hasInstance;
  }

  public GetHomeBootstrap2Response notifyMessage(String notifyMessage) {
    this.notifyMessage = notifyMessage;
    return this;
  }

   /**
   * Get notifyMessage
   * @return notifyMessage
  **/
  @Schema(description = "")
  public String getNotifyMessage() {
    return notifyMessage;
  }

  public void setNotifyMessage(String notifyMessage) {
    this.notifyMessage = notifyMessage;
  }

  public GetHomeBootstrap2Response options(String options) {
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @Schema(description = "")
  public String getOptions() {
    return options;
  }

  public void setOptions(String options) {
    this.options = options;
  }

  public GetHomeBootstrap2Response user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public GetHomeBootstrap2Response watermarkNotified(Boolean watermarkNotified) {
    this.watermarkNotified = watermarkNotified;
    return this;
  }

   /**
   * Get watermarkNotified
   * @return watermarkNotified
  **/
  @Schema(description = "")
  public Boolean isWatermarkNotified() {
    return watermarkNotified;
  }

  public void setWatermarkNotified(Boolean watermarkNotified) {
    this.watermarkNotified = watermarkNotified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetHomeBootstrap2Response getHomeBootstrap2Response = (GetHomeBootstrap2Response) o;
    return Objects.equals(this.comboStatus, getHomeBootstrap2Response.comboStatus) &&
        Objects.equals(this.hasInstance, getHomeBootstrap2Response.hasInstance) &&
        Objects.equals(this.notifyMessage, getHomeBootstrap2Response.notifyMessage) &&
        Objects.equals(this.options, getHomeBootstrap2Response.options) &&
        Objects.equals(this.user, getHomeBootstrap2Response.user) &&
        Objects.equals(this.watermarkNotified, getHomeBootstrap2Response.watermarkNotified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comboStatus, hasInstance, notifyMessage, options, user, watermarkNotified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetHomeBootstrap2Response {\n");
    
    sb.append("    comboStatus: ").append(toIndentedString(comboStatus)).append("\n");
    sb.append("    hasInstance: ").append(toIndentedString(hasInstance)).append("\n");
    sb.append("    notifyMessage: ").append(toIndentedString(notifyMessage)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    watermarkNotified: ").append(toIndentedString(watermarkNotified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
