/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetListRequest
 */



public class GetListRequest {
  @SerializedName("PageNum")
  private Integer pageNum = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("TmplIds")
  private List<String> tmplIds = null;

  public GetListRequest pageNum(Integer pageNum) {
    this.pageNum = pageNum;
    return this;
  }

   /**
   * Get pageNum
   * @return pageNum
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getPageNum() {
    return pageNum;
  }

  public void setPageNum(Integer pageNum) {
    this.pageNum = pageNum;
  }

  public GetListRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public GetListRequest tmplIds(List<String> tmplIds) {
    this.tmplIds = tmplIds;
    return this;
  }

  public GetListRequest addTmplIdsItem(String tmplIdsItem) {
    if (this.tmplIds == null) {
      this.tmplIds = new ArrayList<String>();
    }
    this.tmplIds.add(tmplIdsItem);
    return this;
  }

   /**
   * Get tmplIds
   * @return tmplIds
  **/
  @Schema(description = "")
  public List<String> getTmplIds() {
    return tmplIds;
  }

  public void setTmplIds(List<String> tmplIds) {
    this.tmplIds = tmplIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetListRequest getListRequest = (GetListRequest) o;
    return Objects.equals(this.pageNum, getListRequest.pageNum) &&
        Objects.equals(this.pageSize, getListRequest.pageSize) &&
        Objects.equals(this.tmplIds, getListRequest.tmplIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNum, pageSize, tmplIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetListRequest {\n");
    
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    tmplIds: ").append(toIndentedString(tmplIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
