/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetMaterialTranscodingListRequest
 */



public class GetMaterialTranscodingListRequest {
  @SerializedName("FieldInfos")
  private List<String> fieldInfos = null;

  @SerializedName("MustNotFieldInfos")
  private List<String> mustNotFieldInfos = null;

  @SerializedName("Page")
  private Integer page = null;

  @SerializedName("Perpage")
  private Integer perpage = null;

  @SerializedName("ShouldFieldInfos")
  private List<String> shouldFieldInfos = null;

  @SerializedName("SortName")
  private String sortName = null;

  @SerializedName("SortParams")
  private List<String> sortParams = null;

  @SerializedName("SortReg")
  private Integer sortReg = null;

  @SerializedName("UserData")
  private Integer userData = null;

  public GetMaterialTranscodingListRequest fieldInfos(List<String> fieldInfos) {
    this.fieldInfos = fieldInfos;
    return this;
  }

  public GetMaterialTranscodingListRequest addFieldInfosItem(String fieldInfosItem) {
    if (this.fieldInfos == null) {
      this.fieldInfos = new ArrayList<String>();
    }
    this.fieldInfos.add(fieldInfosItem);
    return this;
  }

   /**
   * Get fieldInfos
   * @return fieldInfos
  **/
  @Schema(description = "")
  public List<String> getFieldInfos() {
    return fieldInfos;
  }

  public void setFieldInfos(List<String> fieldInfos) {
    this.fieldInfos = fieldInfos;
  }

  public GetMaterialTranscodingListRequest mustNotFieldInfos(List<String> mustNotFieldInfos) {
    this.mustNotFieldInfos = mustNotFieldInfos;
    return this;
  }

  public GetMaterialTranscodingListRequest addMustNotFieldInfosItem(String mustNotFieldInfosItem) {
    if (this.mustNotFieldInfos == null) {
      this.mustNotFieldInfos = new ArrayList<String>();
    }
    this.mustNotFieldInfos.add(mustNotFieldInfosItem);
    return this;
  }

   /**
   * Get mustNotFieldInfos
   * @return mustNotFieldInfos
  **/
  @Schema(description = "")
  public List<String> getMustNotFieldInfos() {
    return mustNotFieldInfos;
  }

  public void setMustNotFieldInfos(List<String> mustNotFieldInfos) {
    this.mustNotFieldInfos = mustNotFieldInfos;
  }

  public GetMaterialTranscodingListRequest page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @Schema(description = "")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public GetMaterialTranscodingListRequest perpage(Integer perpage) {
    this.perpage = perpage;
    return this;
  }

   /**
   * Get perpage
   * @return perpage
  **/
  @Schema(description = "")
  public Integer getPerpage() {
    return perpage;
  }

  public void setPerpage(Integer perpage) {
    this.perpage = perpage;
  }

  public GetMaterialTranscodingListRequest shouldFieldInfos(List<String> shouldFieldInfos) {
    this.shouldFieldInfos = shouldFieldInfos;
    return this;
  }

  public GetMaterialTranscodingListRequest addShouldFieldInfosItem(String shouldFieldInfosItem) {
    if (this.shouldFieldInfos == null) {
      this.shouldFieldInfos = new ArrayList<String>();
    }
    this.shouldFieldInfos.add(shouldFieldInfosItem);
    return this;
  }

   /**
   * Get shouldFieldInfos
   * @return shouldFieldInfos
  **/
  @Schema(description = "")
  public List<String> getShouldFieldInfos() {
    return shouldFieldInfos;
  }

  public void setShouldFieldInfos(List<String> shouldFieldInfos) {
    this.shouldFieldInfos = shouldFieldInfos;
  }

  public GetMaterialTranscodingListRequest sortName(String sortName) {
    this.sortName = sortName;
    return this;
  }

   /**
   * Get sortName
   * @return sortName
  **/
  @Schema(description = "")
  public String getSortName() {
    return sortName;
  }

  public void setSortName(String sortName) {
    this.sortName = sortName;
  }

  public GetMaterialTranscodingListRequest sortParams(List<String> sortParams) {
    this.sortParams = sortParams;
    return this;
  }

  public GetMaterialTranscodingListRequest addSortParamsItem(String sortParamsItem) {
    if (this.sortParams == null) {
      this.sortParams = new ArrayList<String>();
    }
    this.sortParams.add(sortParamsItem);
    return this;
  }

   /**
   * Get sortParams
   * @return sortParams
  **/
  @Schema(description = "")
  public List<String> getSortParams() {
    return sortParams;
  }

  public void setSortParams(List<String> sortParams) {
    this.sortParams = sortParams;
  }

  public GetMaterialTranscodingListRequest sortReg(Integer sortReg) {
    this.sortReg = sortReg;
    return this;
  }

   /**
   * Get sortReg
   * @return sortReg
  **/
  @Schema(description = "")
  public Integer getSortReg() {
    return sortReg;
  }

  public void setSortReg(Integer sortReg) {
    this.sortReg = sortReg;
  }

  public GetMaterialTranscodingListRequest userData(Integer userData) {
    this.userData = userData;
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  @Schema(description = "")
  public Integer getUserData() {
    return userData;
  }

  public void setUserData(Integer userData) {
    this.userData = userData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMaterialTranscodingListRequest getMaterialTranscodingListRequest = (GetMaterialTranscodingListRequest) o;
    return Objects.equals(this.fieldInfos, getMaterialTranscodingListRequest.fieldInfos) &&
        Objects.equals(this.mustNotFieldInfos, getMaterialTranscodingListRequest.mustNotFieldInfos) &&
        Objects.equals(this.page, getMaterialTranscodingListRequest.page) &&
        Objects.equals(this.perpage, getMaterialTranscodingListRequest.perpage) &&
        Objects.equals(this.shouldFieldInfos, getMaterialTranscodingListRequest.shouldFieldInfos) &&
        Objects.equals(this.sortName, getMaterialTranscodingListRequest.sortName) &&
        Objects.equals(this.sortParams, getMaterialTranscodingListRequest.sortParams) &&
        Objects.equals(this.sortReg, getMaterialTranscodingListRequest.sortReg) &&
        Objects.equals(this.userData, getMaterialTranscodingListRequest.userData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldInfos, mustNotFieldInfos, page, perpage, shouldFieldInfos, sortName, sortParams, sortReg, userData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMaterialTranscodingListRequest {\n");
    
    sb.append("    fieldInfos: ").append(toIndentedString(fieldInfos)).append("\n");
    sb.append("    mustNotFieldInfos: ").append(toIndentedString(mustNotFieldInfos)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perpage: ").append(toIndentedString(perpage)).append("\n");
    sb.append("    shouldFieldInfos: ").append(toIndentedString(shouldFieldInfos)).append("\n");
    sb.append("    sortName: ").append(toIndentedString(sortName)).append("\n");
    sb.append("    sortParams: ").append(toIndentedString(sortParams)).append("\n");
    sb.append("    sortReg: ").append(toIndentedString(sortReg)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
