/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetPublicTemplateListResponse
 */



public class GetPublicTemplateListResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("Medias")
  private List<String> medias = null;

  @SerializedName("Total")
  private Integer total = null;

  public GetPublicTemplateListResponse medias(List<String> medias) {
    this.medias = medias;
    return this;
  }

  public GetPublicTemplateListResponse addMediasItem(String mediasItem) {
    if (this.medias == null) {
      this.medias = new ArrayList<String>();
    }
    this.medias.add(mediasItem);
    return this;
  }

   /**
   * Get medias
   * @return medias
  **/
  @Schema(description = "")
  public List<String> getMedias() {
    return medias;
  }

  public void setMedias(List<String> medias) {
    this.medias = medias;
  }

  public GetPublicTemplateListResponse total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(description = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPublicTemplateListResponse getPublicTemplateListResponse = (GetPublicTemplateListResponse) o;
    return Objects.equals(this.medias, getPublicTemplateListResponse.medias) &&
        Objects.equals(this.total, getPublicTemplateListResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(medias, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPublicTemplateListResponse {\n");
    
    sb.append("    medias: ").append(toIndentedString(medias)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
