/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetPublishDraftRequest
 */



public class GetPublishDraftRequest {
  @SerializedName("MediaId")
  private String mediaId = null;

  @SerializedName("PublishId")
  private String publishId = null;

  @SerializedName("SourceType")
  private Integer sourceType = null;

  public GetPublishDraftRequest mediaId(String mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Get mediaId
   * @return mediaId
  **/
  @Schema(description = "")
  public String getMediaId() {
    return mediaId;
  }

  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }

  public GetPublishDraftRequest publishId(String publishId) {
    this.publishId = publishId;
    return this;
  }

   /**
   * Get publishId
   * @return publishId
  **/
  @Schema(description = "")
  public String getPublishId() {
    return publishId;
  }

  public void setPublishId(String publishId) {
    this.publishId = publishId;
  }

  public GetPublishDraftRequest sourceType(Integer sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @Schema(description = "")
  public Integer getSourceType() {
    return sourceType;
  }

  public void setSourceType(Integer sourceType) {
    this.sourceType = sourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPublishDraftRequest getPublishDraftRequest = (GetPublishDraftRequest) o;
    return Objects.equals(this.mediaId, getPublishDraftRequest.mediaId) &&
        Objects.equals(this.publishId, getPublishDraftRequest.publishId) &&
        Objects.equals(this.sourceType, getPublishDraftRequest.sourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaId, publishId, sourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPublishDraftRequest {\n");
    
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    publishId: ").append(toIndentedString(publishId)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
