/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetSpecialZoneConfigResponse
 */



public class GetSpecialZoneConfigResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("CategoryCode")
  private String categoryCode = null;

  @SerializedName("Horse")
  private String horse = null;

  @SerializedName("IsSpringFestival")
  private Boolean isSpringFestival = null;

  @SerializedName("Lantern")
  private String lantern = null;

  @SerializedName("PlaceholderCount")
  private Integer placeholderCount = null;

  public GetSpecialZoneConfigResponse categoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
    return this;
  }

   /**
   * Get categoryCode
   * @return categoryCode
  **/
  @Schema(description = "")
  public String getCategoryCode() {
    return categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  public GetSpecialZoneConfigResponse horse(String horse) {
    this.horse = horse;
    return this;
  }

   /**
   * Get horse
   * @return horse
  **/
  @Schema(description = "")
  public String getHorse() {
    return horse;
  }

  public void setHorse(String horse) {
    this.horse = horse;
  }

  public GetSpecialZoneConfigResponse isSpringFestival(Boolean isSpringFestival) {
    this.isSpringFestival = isSpringFestival;
    return this;
  }

   /**
   * Get isSpringFestival
   * @return isSpringFestival
  **/
  @Schema(description = "")
  public Boolean isIsSpringFestival() {
    return isSpringFestival;
  }

  public void setIsSpringFestival(Boolean isSpringFestival) {
    this.isSpringFestival = isSpringFestival;
  }

  public GetSpecialZoneConfigResponse lantern(String lantern) {
    this.lantern = lantern;
    return this;
  }

   /**
   * Get lantern
   * @return lantern
  **/
  @Schema(description = "")
  public String getLantern() {
    return lantern;
  }

  public void setLantern(String lantern) {
    this.lantern = lantern;
  }

  public GetSpecialZoneConfigResponse placeholderCount(Integer placeholderCount) {
    this.placeholderCount = placeholderCount;
    return this;
  }

   /**
   * Get placeholderCount
   * @return placeholderCount
  **/
  @Schema(description = "")
  public Integer getPlaceholderCount() {
    return placeholderCount;
  }

  public void setPlaceholderCount(Integer placeholderCount) {
    this.placeholderCount = placeholderCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSpecialZoneConfigResponse getSpecialZoneConfigResponse = (GetSpecialZoneConfigResponse) o;
    return Objects.equals(this.categoryCode, getSpecialZoneConfigResponse.categoryCode) &&
        Objects.equals(this.horse, getSpecialZoneConfigResponse.horse) &&
        Objects.equals(this.isSpringFestival, getSpecialZoneConfigResponse.isSpringFestival) &&
        Objects.equals(this.lantern, getSpecialZoneConfigResponse.lantern) &&
        Objects.equals(this.placeholderCount, getSpecialZoneConfigResponse.placeholderCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryCode, horse, isSpringFestival, lantern, placeholderCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSpecialZoneConfigResponse {\n");
    
    sb.append("    categoryCode: ").append(toIndentedString(categoryCode)).append("\n");
    sb.append("    horse: ").append(toIndentedString(horse)).append("\n");
    sb.append("    isSpringFestival: ").append(toIndentedString(isSpringFestival)).append("\n");
    sb.append("    lantern: ").append(toIndentedString(lantern)).append("\n");
    sb.append("    placeholderCount: ").append(toIndentedString(placeholderCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
