/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ListPromptResponse
 */



public class ListPromptResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("Prompts")
  private String prompts = null;

  public ListPromptResponse prompts(String prompts) {
    this.prompts = prompts;
    return this;
  }

   /**
   * Get prompts
   * @return prompts
  **/
  @Schema(description = "")
  public String getPrompts() {
    return prompts;
  }

  public void setPrompts(String prompts) {
    this.prompts = prompts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListPromptResponse listPromptResponse = (ListPromptResponse) o;
    return Objects.equals(this.prompts, listPromptResponse.prompts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListPromptResponse {\n");
    
    sb.append("    prompts: ").append(toIndentedString(prompts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
