/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ListAvatarVoiceRequest
 */



public class ListAvatarVoiceRequest {
  @SerializedName("AgeGroupFilter")
  private List<String> ageGroupFilter = null;

  @SerializedName("GenderFilter")
  private List<String> genderFilter = null;

  @SerializedName("LanguageFilter")
  private List<String> languageFilter = null;

  @SerializedName("NameFilter")
  private String nameFilter = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("StyleIdFilter")
  private List<String> styleIdFilter = null;

  public ListAvatarVoiceRequest ageGroupFilter(List<String> ageGroupFilter) {
    this.ageGroupFilter = ageGroupFilter;
    return this;
  }

  public ListAvatarVoiceRequest addAgeGroupFilterItem(String ageGroupFilterItem) {
    if (this.ageGroupFilter == null) {
      this.ageGroupFilter = new ArrayList<String>();
    }
    this.ageGroupFilter.add(ageGroupFilterItem);
    return this;
  }

   /**
   * Get ageGroupFilter
   * @return ageGroupFilter
  **/
  @Schema(description = "")
  public List<String> getAgeGroupFilter() {
    return ageGroupFilter;
  }

  public void setAgeGroupFilter(List<String> ageGroupFilter) {
    this.ageGroupFilter = ageGroupFilter;
  }

  public ListAvatarVoiceRequest genderFilter(List<String> genderFilter) {
    this.genderFilter = genderFilter;
    return this;
  }

  public ListAvatarVoiceRequest addGenderFilterItem(String genderFilterItem) {
    if (this.genderFilter == null) {
      this.genderFilter = new ArrayList<String>();
    }
    this.genderFilter.add(genderFilterItem);
    return this;
  }

   /**
   * Get genderFilter
   * @return genderFilter
  **/
  @Schema(description = "")
  public List<String> getGenderFilter() {
    return genderFilter;
  }

  public void setGenderFilter(List<String> genderFilter) {
    this.genderFilter = genderFilter;
  }

  public ListAvatarVoiceRequest languageFilter(List<String> languageFilter) {
    this.languageFilter = languageFilter;
    return this;
  }

  public ListAvatarVoiceRequest addLanguageFilterItem(String languageFilterItem) {
    if (this.languageFilter == null) {
      this.languageFilter = new ArrayList<String>();
    }
    this.languageFilter.add(languageFilterItem);
    return this;
  }

   /**
   * Get languageFilter
   * @return languageFilter
  **/
  @Schema(description = "")
  public List<String> getLanguageFilter() {
    return languageFilter;
  }

  public void setLanguageFilter(List<String> languageFilter) {
    this.languageFilter = languageFilter;
  }

  public ListAvatarVoiceRequest nameFilter(String nameFilter) {
    this.nameFilter = nameFilter;
    return this;
  }

   /**
   * Get nameFilter
   * @return nameFilter
  **/
  @Schema(description = "")
  public String getNameFilter() {
    return nameFilter;
  }

  public void setNameFilter(String nameFilter) {
    this.nameFilter = nameFilter;
  }

  public ListAvatarVoiceRequest pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public ListAvatarVoiceRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public ListAvatarVoiceRequest styleIdFilter(List<String> styleIdFilter) {
    this.styleIdFilter = styleIdFilter;
    return this;
  }

  public ListAvatarVoiceRequest addStyleIdFilterItem(String styleIdFilterItem) {
    if (this.styleIdFilter == null) {
      this.styleIdFilter = new ArrayList<String>();
    }
    this.styleIdFilter.add(styleIdFilterItem);
    return this;
  }

   /**
   * Get styleIdFilter
   * @return styleIdFilter
  **/
  @Schema(description = "")
  public List<String> getStyleIdFilter() {
    return styleIdFilter;
  }

  public void setStyleIdFilter(List<String> styleIdFilter) {
    this.styleIdFilter = styleIdFilter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAvatarVoiceRequest listAvatarVoiceRequest = (ListAvatarVoiceRequest) o;
    return Objects.equals(this.ageGroupFilter, listAvatarVoiceRequest.ageGroupFilter) &&
        Objects.equals(this.genderFilter, listAvatarVoiceRequest.genderFilter) &&
        Objects.equals(this.languageFilter, listAvatarVoiceRequest.languageFilter) &&
        Objects.equals(this.nameFilter, listAvatarVoiceRequest.nameFilter) &&
        Objects.equals(this.pageNumber, listAvatarVoiceRequest.pageNumber) &&
        Objects.equals(this.pageSize, listAvatarVoiceRequest.pageSize) &&
        Objects.equals(this.styleIdFilter, listAvatarVoiceRequest.styleIdFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ageGroupFilter, genderFilter, languageFilter, nameFilter, pageNumber, pageSize, styleIdFilter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAvatarVoiceRequest {\n");
    
    sb.append("    ageGroupFilter: ").append(toIndentedString(ageGroupFilter)).append("\n");
    sb.append("    genderFilter: ").append(toIndentedString(genderFilter)).append("\n");
    sb.append("    languageFilter: ").append(toIndentedString(languageFilter)).append("\n");
    sb.append("    nameFilter: ").append(toIndentedString(nameFilter)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    styleIdFilter: ").append(toIndentedString(styleIdFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
