/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * QuerySelectItemResponse
 */



public class QuerySelectItemResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("ConsumerItems")
  private List<String> consumerItems = null;

  @SerializedName("Users")
  private List<String> users = null;

  public QuerySelectItemResponse consumerItems(List<String> consumerItems) {
    this.consumerItems = consumerItems;
    return this;
  }

  public QuerySelectItemResponse addConsumerItemsItem(String consumerItemsItem) {
    if (this.consumerItems == null) {
      this.consumerItems = new ArrayList<String>();
    }
    this.consumerItems.add(consumerItemsItem);
    return this;
  }

   /**
   * Get consumerItems
   * @return consumerItems
  **/
  @Schema(description = "")
  public List<String> getConsumerItems() {
    return consumerItems;
  }

  public void setConsumerItems(List<String> consumerItems) {
    this.consumerItems = consumerItems;
  }

  public QuerySelectItemResponse users(List<String> users) {
    this.users = users;
    return this;
  }

  public QuerySelectItemResponse addUsersItem(String usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<String>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @Schema(description = "")
  public List<String> getUsers() {
    return users;
  }

  public void setUsers(List<String> users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuerySelectItemResponse querySelectItemResponse = (QuerySelectItemResponse) o;
    return Objects.equals(this.consumerItems, querySelectItemResponse.consumerItems) &&
        Objects.equals(this.users, querySelectItemResponse.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerItems, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuerySelectItemResponse {\n");
    
    sb.append("    consumerItems: ").append(toIndentedString(consumerItems)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
