/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * SearchAssetRequest
 */



public class SearchAssetRequest {
  @SerializedName("AutoDel")
  private Integer autoDel = null;

  @SerializedName("ExcludeInfos")
  private List<String> excludeInfos = null;

  @SerializedName("Extra")
  private String extra = null;

  @SerializedName("FetchInternalDomain")
  private Boolean fetchInternalDomain = null;

  @SerializedName("FieldInfos")
  private List<String> fieldInfos = null;

  @SerializedName("FullPath")
  private String fullPath = null;

  @SerializedName("MaterialType")
  private String materialType = null;

  @SerializedName("NeedCount")
  private Integer needCount = null;

  @SerializedName("Owner")
  private String owner = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("Query")
  private String query = null;

  @SerializedName("SortName")
  private String sortName = null;

  @SerializedName("SortParams")
  private List<String> sortParams = null;

  @SerializedName("SortReg")
  private Integer sortReg = null;

  public SearchAssetRequest autoDel(Integer autoDel) {
    this.autoDel = autoDel;
    return this;
  }

   /**
   * Get autoDel
   * @return autoDel
  **/
  @Schema(description = "")
  public Integer getAutoDel() {
    return autoDel;
  }

  public void setAutoDel(Integer autoDel) {
    this.autoDel = autoDel;
  }

  public SearchAssetRequest excludeInfos(List<String> excludeInfos) {
    this.excludeInfos = excludeInfos;
    return this;
  }

  public SearchAssetRequest addExcludeInfosItem(String excludeInfosItem) {
    if (this.excludeInfos == null) {
      this.excludeInfos = new ArrayList<String>();
    }
    this.excludeInfos.add(excludeInfosItem);
    return this;
  }

   /**
   * Get excludeInfos
   * @return excludeInfos
  **/
  @Schema(description = "")
  public List<String> getExcludeInfos() {
    return excludeInfos;
  }

  public void setExcludeInfos(List<String> excludeInfos) {
    this.excludeInfos = excludeInfos;
  }

  public SearchAssetRequest extra(String extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Get extra
   * @return extra
  **/
  @Schema(description = "")
  public String getExtra() {
    return extra;
  }

  public void setExtra(String extra) {
    this.extra = extra;
  }

  public SearchAssetRequest fetchInternalDomain(Boolean fetchInternalDomain) {
    this.fetchInternalDomain = fetchInternalDomain;
    return this;
  }

   /**
   * Get fetchInternalDomain
   * @return fetchInternalDomain
  **/
  @Schema(description = "")
  public Boolean isFetchInternalDomain() {
    return fetchInternalDomain;
  }

  public void setFetchInternalDomain(Boolean fetchInternalDomain) {
    this.fetchInternalDomain = fetchInternalDomain;
  }

  public SearchAssetRequest fieldInfos(List<String> fieldInfos) {
    this.fieldInfos = fieldInfos;
    return this;
  }

  public SearchAssetRequest addFieldInfosItem(String fieldInfosItem) {
    if (this.fieldInfos == null) {
      this.fieldInfos = new ArrayList<String>();
    }
    this.fieldInfos.add(fieldInfosItem);
    return this;
  }

   /**
   * Get fieldInfos
   * @return fieldInfos
  **/
  @Schema(description = "")
  public List<String> getFieldInfos() {
    return fieldInfos;
  }

  public void setFieldInfos(List<String> fieldInfos) {
    this.fieldInfos = fieldInfos;
  }

  public SearchAssetRequest fullPath(String fullPath) {
    this.fullPath = fullPath;
    return this;
  }

   /**
   * Get fullPath
   * @return fullPath
  **/
  @Schema(description = "")
  public String getFullPath() {
    return fullPath;
  }

  public void setFullPath(String fullPath) {
    this.fullPath = fullPath;
  }

  public SearchAssetRequest materialType(String materialType) {
    this.materialType = materialType;
    return this;
  }

   /**
   * Get materialType
   * @return materialType
  **/
  @Schema(description = "")
  public String getMaterialType() {
    return materialType;
  }

  public void setMaterialType(String materialType) {
    this.materialType = materialType;
  }

  public SearchAssetRequest needCount(Integer needCount) {
    this.needCount = needCount;
    return this;
  }

   /**
   * Get needCount
   * @return needCount
  **/
  @Schema(description = "")
  public Integer getNeedCount() {
    return needCount;
  }

  public void setNeedCount(Integer needCount) {
    this.needCount = needCount;
  }

  public SearchAssetRequest owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(description = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public SearchAssetRequest pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public SearchAssetRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public SearchAssetRequest query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @Schema(description = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public SearchAssetRequest sortName(String sortName) {
    this.sortName = sortName;
    return this;
  }

   /**
   * Get sortName
   * @return sortName
  **/
  @Schema(description = "")
  public String getSortName() {
    return sortName;
  }

  public void setSortName(String sortName) {
    this.sortName = sortName;
  }

  public SearchAssetRequest sortParams(List<String> sortParams) {
    this.sortParams = sortParams;
    return this;
  }

  public SearchAssetRequest addSortParamsItem(String sortParamsItem) {
    if (this.sortParams == null) {
      this.sortParams = new ArrayList<String>();
    }
    this.sortParams.add(sortParamsItem);
    return this;
  }

   /**
   * Get sortParams
   * @return sortParams
  **/
  @Schema(description = "")
  public List<String> getSortParams() {
    return sortParams;
  }

  public void setSortParams(List<String> sortParams) {
    this.sortParams = sortParams;
  }

  public SearchAssetRequest sortReg(Integer sortReg) {
    this.sortReg = sortReg;
    return this;
  }

   /**
   * Get sortReg
   * @return sortReg
  **/
  @Schema(description = "")
  public Integer getSortReg() {
    return sortReg;
  }

  public void setSortReg(Integer sortReg) {
    this.sortReg = sortReg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchAssetRequest searchAssetRequest = (SearchAssetRequest) o;
    return Objects.equals(this.autoDel, searchAssetRequest.autoDel) &&
        Objects.equals(this.excludeInfos, searchAssetRequest.excludeInfos) &&
        Objects.equals(this.extra, searchAssetRequest.extra) &&
        Objects.equals(this.fetchInternalDomain, searchAssetRequest.fetchInternalDomain) &&
        Objects.equals(this.fieldInfos, searchAssetRequest.fieldInfos) &&
        Objects.equals(this.fullPath, searchAssetRequest.fullPath) &&
        Objects.equals(this.materialType, searchAssetRequest.materialType) &&
        Objects.equals(this.needCount, searchAssetRequest.needCount) &&
        Objects.equals(this.owner, searchAssetRequest.owner) &&
        Objects.equals(this.pageNumber, searchAssetRequest.pageNumber) &&
        Objects.equals(this.pageSize, searchAssetRequest.pageSize) &&
        Objects.equals(this.query, searchAssetRequest.query) &&
        Objects.equals(this.sortName, searchAssetRequest.sortName) &&
        Objects.equals(this.sortParams, searchAssetRequest.sortParams) &&
        Objects.equals(this.sortReg, searchAssetRequest.sortReg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoDel, excludeInfos, extra, fetchInternalDomain, fieldInfos, fullPath, materialType, needCount, owner, pageNumber, pageSize, query, sortName, sortParams, sortReg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchAssetRequest {\n");
    
    sb.append("    autoDel: ").append(toIndentedString(autoDel)).append("\n");
    sb.append("    excludeInfos: ").append(toIndentedString(excludeInfos)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    fetchInternalDomain: ").append(toIndentedString(fetchInternalDomain)).append("\n");
    sb.append("    fieldInfos: ").append(toIndentedString(fieldInfos)).append("\n");
    sb.append("    fullPath: ").append(toIndentedString(fullPath)).append("\n");
    sb.append("    materialType: ").append(toIndentedString(materialType)).append("\n");
    sb.append("    needCount: ").append(toIndentedString(needCount)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    sortName: ").append(toIndentedString(sortName)).append("\n");
    sb.append("    sortParams: ").append(toIndentedString(sortParams)).append("\n");
    sb.append("    sortReg: ").append(toIndentedString(sortReg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
