/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * SetWatermarkSwitchStatusRequest
 */



public class SetWatermarkSwitchStatusRequest {
  @SerializedName("BrightWatermark")
  private Boolean brightWatermark = null;

  @SerializedName("BroadcastServiceProvider")
  private Boolean broadcastServiceProvider = null;

  @SerializedName("Company")
  private String company = null;

  @SerializedName("ComposeServiceProvider")
  private Boolean composeServiceProvider = null;

  @SerializedName("DarkWatermark")
  private Boolean darkWatermark = null;

  @SerializedName("SocialCreditCode")
  private String socialCreditCode = null;

  public SetWatermarkSwitchStatusRequest brightWatermark(Boolean brightWatermark) {
    this.brightWatermark = brightWatermark;
    return this;
  }

   /**
   * Get brightWatermark
   * @return brightWatermark
  **/
  @Schema(description = "")
  public Boolean isBrightWatermark() {
    return brightWatermark;
  }

  public void setBrightWatermark(Boolean brightWatermark) {
    this.brightWatermark = brightWatermark;
  }

  public SetWatermarkSwitchStatusRequest broadcastServiceProvider(Boolean broadcastServiceProvider) {
    this.broadcastServiceProvider = broadcastServiceProvider;
    return this;
  }

   /**
   * Get broadcastServiceProvider
   * @return broadcastServiceProvider
  **/
  @Schema(description = "")
  public Boolean isBroadcastServiceProvider() {
    return broadcastServiceProvider;
  }

  public void setBroadcastServiceProvider(Boolean broadcastServiceProvider) {
    this.broadcastServiceProvider = broadcastServiceProvider;
  }

  public SetWatermarkSwitchStatusRequest company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @Schema(description = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public SetWatermarkSwitchStatusRequest composeServiceProvider(Boolean composeServiceProvider) {
    this.composeServiceProvider = composeServiceProvider;
    return this;
  }

   /**
   * Get composeServiceProvider
   * @return composeServiceProvider
  **/
  @Schema(description = "")
  public Boolean isComposeServiceProvider() {
    return composeServiceProvider;
  }

  public void setComposeServiceProvider(Boolean composeServiceProvider) {
    this.composeServiceProvider = composeServiceProvider;
  }

  public SetWatermarkSwitchStatusRequest darkWatermark(Boolean darkWatermark) {
    this.darkWatermark = darkWatermark;
    return this;
  }

   /**
   * Get darkWatermark
   * @return darkWatermark
  **/
  @Schema(description = "")
  public Boolean isDarkWatermark() {
    return darkWatermark;
  }

  public void setDarkWatermark(Boolean darkWatermark) {
    this.darkWatermark = darkWatermark;
  }

  public SetWatermarkSwitchStatusRequest socialCreditCode(String socialCreditCode) {
    this.socialCreditCode = socialCreditCode;
    return this;
  }

   /**
   * Get socialCreditCode
   * @return socialCreditCode
  **/
  @Schema(description = "")
  public String getSocialCreditCode() {
    return socialCreditCode;
  }

  public void setSocialCreditCode(String socialCreditCode) {
    this.socialCreditCode = socialCreditCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetWatermarkSwitchStatusRequest setWatermarkSwitchStatusRequest = (SetWatermarkSwitchStatusRequest) o;
    return Objects.equals(this.brightWatermark, setWatermarkSwitchStatusRequest.brightWatermark) &&
        Objects.equals(this.broadcastServiceProvider, setWatermarkSwitchStatusRequest.broadcastServiceProvider) &&
        Objects.equals(this.company, setWatermarkSwitchStatusRequest.company) &&
        Objects.equals(this.composeServiceProvider, setWatermarkSwitchStatusRequest.composeServiceProvider) &&
        Objects.equals(this.darkWatermark, setWatermarkSwitchStatusRequest.darkWatermark) &&
        Objects.equals(this.socialCreditCode, setWatermarkSwitchStatusRequest.socialCreditCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brightWatermark, broadcastServiceProvider, company, composeServiceProvider, darkWatermark, socialCreditCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetWatermarkSwitchStatusRequest {\n");
    
    sb.append("    brightWatermark: ").append(toIndentedString(brightWatermark)).append("\n");
    sb.append("    broadcastServiceProvider: ").append(toIndentedString(broadcastServiceProvider)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    composeServiceProvider: ").append(toIndentedString(composeServiceProvider)).append("\n");
    sb.append("    darkWatermark: ").append(toIndentedString(darkWatermark)).append("\n");
    sb.append("    socialCreditCode: ").append(toIndentedString(socialCreditCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
