/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * SubmitPublishRequest
 */



public class SubmitPublishRequest {
  @SerializedName("PublishId")
  private Integer publishId = null;

  public SubmitPublishRequest publishId(Integer publishId) {
    this.publishId = publishId;
    return this;
  }

   /**
   * Get publishId
   * @return publishId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getPublishId() {
    return publishId;
  }

  public void setPublishId(Integer publishId) {
    this.publishId = publishId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitPublishRequest submitPublishRequest = (SubmitPublishRequest) o;
    return Objects.equals(this.publishId, submitPublishRequest.publishId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publishId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitPublishRequest {\n");
    
    sb.append("    publishId: ").append(toIndentedString(publishId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
