/*
 * kickart
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.kickart.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * UpdateCompositionResponse
 */



public class UpdateCompositionResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("ParamDiff")
  private String paramDiff = null;

  public UpdateCompositionResponse paramDiff(String paramDiff) {
    this.paramDiff = paramDiff;
    return this;
  }

   /**
   * Get paramDiff
   * @return paramDiff
  **/
  @Schema(description = "")
  public String getParamDiff() {
    return paramDiff;
  }

  public void setParamDiff(String paramDiff) {
    this.paramDiff = paramDiff;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCompositionResponse updateCompositionResponse = (UpdateCompositionResponse) o;
    return Objects.equals(this.paramDiff, updateCompositionResponse.paramDiff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paramDiff);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCompositionResponse {\n");
    
    sb.append("    paramDiff: ").append(toIndentedString(paramDiff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
