/*
 * ecs20251101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ecs20251101.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ecs20251101.model.MemoryForDescribeInstanceTypesOutput;
import com.byteplus.ecs20251101.model.NetworkForDescribeInstanceTypesOutput;
import com.byteplus.ecs20251101.model.ProcessorForDescribeInstanceTypesOutput;
import com.byteplus.ecs20251101.model.VolumeForDescribeInstanceTypesOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * InstanceTypeForDescribeInstanceTypesOutput
 */



public class InstanceTypeForDescribeInstanceTypesOutput {
  @SerializedName("InstanceTypeFamily")
  private String instanceTypeFamily = null;

  @SerializedName("InstanceTypeId")
  private String instanceTypeId = null;

  @SerializedName("Memory")
  private MemoryForDescribeInstanceTypesOutput memory = null;

  @SerializedName("Network")
  private NetworkForDescribeInstanceTypesOutput network = null;

  @SerializedName("Processor")
  private ProcessorForDescribeInstanceTypesOutput processor = null;

  @SerializedName("Volume")
  private VolumeForDescribeInstanceTypesOutput volume = null;

  public InstanceTypeForDescribeInstanceTypesOutput instanceTypeFamily(String instanceTypeFamily) {
    this.instanceTypeFamily = instanceTypeFamily;
    return this;
  }

   /**
   * Get instanceTypeFamily
   * @return instanceTypeFamily
  **/
  @Schema(description = "")
  public String getInstanceTypeFamily() {
    return instanceTypeFamily;
  }

  public void setInstanceTypeFamily(String instanceTypeFamily) {
    this.instanceTypeFamily = instanceTypeFamily;
  }

  public InstanceTypeForDescribeInstanceTypesOutput instanceTypeId(String instanceTypeId) {
    this.instanceTypeId = instanceTypeId;
    return this;
  }

   /**
   * Get instanceTypeId
   * @return instanceTypeId
  **/
  @Schema(description = "")
  public String getInstanceTypeId() {
    return instanceTypeId;
  }

  public void setInstanceTypeId(String instanceTypeId) {
    this.instanceTypeId = instanceTypeId;
  }

  public InstanceTypeForDescribeInstanceTypesOutput memory(MemoryForDescribeInstanceTypesOutput memory) {
    this.memory = memory;
    return this;
  }

   /**
   * Get memory
   * @return memory
  **/
  @Valid
  @Schema(description = "")
  public MemoryForDescribeInstanceTypesOutput getMemory() {
    return memory;
  }

  public void setMemory(MemoryForDescribeInstanceTypesOutput memory) {
    this.memory = memory;
  }

  public InstanceTypeForDescribeInstanceTypesOutput network(NetworkForDescribeInstanceTypesOutput network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Valid
  @Schema(description = "")
  public NetworkForDescribeInstanceTypesOutput getNetwork() {
    return network;
  }

  public void setNetwork(NetworkForDescribeInstanceTypesOutput network) {
    this.network = network;
  }

  public InstanceTypeForDescribeInstanceTypesOutput processor(ProcessorForDescribeInstanceTypesOutput processor) {
    this.processor = processor;
    return this;
  }

   /**
   * Get processor
   * @return processor
  **/
  @Valid
  @Schema(description = "")
  public ProcessorForDescribeInstanceTypesOutput getProcessor() {
    return processor;
  }

  public void setProcessor(ProcessorForDescribeInstanceTypesOutput processor) {
    this.processor = processor;
  }

  public InstanceTypeForDescribeInstanceTypesOutput volume(VolumeForDescribeInstanceTypesOutput volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @Valid
  @Schema(description = "")
  public VolumeForDescribeInstanceTypesOutput getVolume() {
    return volume;
  }

  public void setVolume(VolumeForDescribeInstanceTypesOutput volume) {
    this.volume = volume;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceTypeForDescribeInstanceTypesOutput instanceTypeForDescribeInstanceTypesOutput = (InstanceTypeForDescribeInstanceTypesOutput) o;
    return Objects.equals(this.instanceTypeFamily, instanceTypeForDescribeInstanceTypesOutput.instanceTypeFamily) &&
        Objects.equals(this.instanceTypeId, instanceTypeForDescribeInstanceTypesOutput.instanceTypeId) &&
        Objects.equals(this.memory, instanceTypeForDescribeInstanceTypesOutput.memory) &&
        Objects.equals(this.network, instanceTypeForDescribeInstanceTypesOutput.network) &&
        Objects.equals(this.processor, instanceTypeForDescribeInstanceTypesOutput.processor) &&
        Objects.equals(this.volume, instanceTypeForDescribeInstanceTypesOutput.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceTypeFamily, instanceTypeId, memory, network, processor, volume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceTypeForDescribeInstanceTypesOutput {\n");
    
    sb.append("    instanceTypeFamily: ").append(toIndentedString(instanceTypeFamily)).append("\n");
    sb.append("    instanceTypeId: ").append(toIndentedString(instanceTypeId)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
