/*
 * ecs20251101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ecs20251101.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ecs20251101.model.NetworkInterfaceForDescribeInstancesOutput;
import com.byteplus.ecs20251101.model.TagForDescribeInstancesOutput;
import com.byteplus.ecs20251101.model.VolumeForDescribeInstancesOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * InstanceForDescribeInstancesOutput
 */



public class InstanceForDescribeInstancesOutput {
  @SerializedName("Cpus")
  private Integer cpus = null;

  @SerializedName("CreatedAt")
  private String createdAt = null;

  @SerializedName("ImageId")
  private String imageId = null;

  @SerializedName("InstanceChargeType")
  private String instanceChargeType = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("InstanceName")
  private String instanceName = null;

  @SerializedName("InstanceTypeId")
  private String instanceTypeId = null;

  @SerializedName("MemorySize")
  private Integer memorySize = null;

  @SerializedName("NetworkInterfaces")
  private List<NetworkInterfaceForDescribeInstancesOutput> networkInterfaces = null;

  @SerializedName("OsName")
  private String osName = null;

  @SerializedName("OsType")
  private String osType = null;

  @SerializedName("ProjectName")
  private String projectName = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("Tags")
  private List<TagForDescribeInstancesOutput> tags = null;

  @SerializedName("Volumes")
  private List<VolumeForDescribeInstancesOutput> volumes = null;

  @SerializedName("VpcId")
  private String vpcId = null;

  @SerializedName("ZoneId")
  private String zoneId = null;

  public InstanceForDescribeInstancesOutput cpus(Integer cpus) {
    this.cpus = cpus;
    return this;
  }

   /**
   * Get cpus
   * @return cpus
  **/
  @Schema(description = "")
  public Integer getCpus() {
    return cpus;
  }

  public void setCpus(Integer cpus) {
    this.cpus = cpus;
  }

  public InstanceForDescribeInstancesOutput createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public InstanceForDescribeInstancesOutput imageId(String imageId) {
    this.imageId = imageId;
    return this;
  }

   /**
   * Get imageId
   * @return imageId
  **/
  @Schema(description = "")
  public String getImageId() {
    return imageId;
  }

  public void setImageId(String imageId) {
    this.imageId = imageId;
  }

  public InstanceForDescribeInstancesOutput instanceChargeType(String instanceChargeType) {
    this.instanceChargeType = instanceChargeType;
    return this;
  }

   /**
   * Get instanceChargeType
   * @return instanceChargeType
  **/
  @Schema(description = "")
  public String getInstanceChargeType() {
    return instanceChargeType;
  }

  public void setInstanceChargeType(String instanceChargeType) {
    this.instanceChargeType = instanceChargeType;
  }

  public InstanceForDescribeInstancesOutput instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @Schema(description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public InstanceForDescribeInstancesOutput instanceName(String instanceName) {
    this.instanceName = instanceName;
    return this;
  }

   /**
   * Get instanceName
   * @return instanceName
  **/
  @Schema(description = "")
  public String getInstanceName() {
    return instanceName;
  }

  public void setInstanceName(String instanceName) {
    this.instanceName = instanceName;
  }

  public InstanceForDescribeInstancesOutput instanceTypeId(String instanceTypeId) {
    this.instanceTypeId = instanceTypeId;
    return this;
  }

   /**
   * Get instanceTypeId
   * @return instanceTypeId
  **/
  @Schema(description = "")
  public String getInstanceTypeId() {
    return instanceTypeId;
  }

  public void setInstanceTypeId(String instanceTypeId) {
    this.instanceTypeId = instanceTypeId;
  }

  public InstanceForDescribeInstancesOutput memorySize(Integer memorySize) {
    this.memorySize = memorySize;
    return this;
  }

   /**
   * Get memorySize
   * @return memorySize
  **/
  @Schema(description = "")
  public Integer getMemorySize() {
    return memorySize;
  }

  public void setMemorySize(Integer memorySize) {
    this.memorySize = memorySize;
  }

  public InstanceForDescribeInstancesOutput networkInterfaces(List<NetworkInterfaceForDescribeInstancesOutput> networkInterfaces) {
    this.networkInterfaces = networkInterfaces;
    return this;
  }

  public InstanceForDescribeInstancesOutput addNetworkInterfacesItem(NetworkInterfaceForDescribeInstancesOutput networkInterfacesItem) {
    if (this.networkInterfaces == null) {
      this.networkInterfaces = new ArrayList<NetworkInterfaceForDescribeInstancesOutput>();
    }
    this.networkInterfaces.add(networkInterfacesItem);
    return this;
  }

   /**
   * Get networkInterfaces
   * @return networkInterfaces
  **/
  @Valid
  @Schema(description = "")
  public List<NetworkInterfaceForDescribeInstancesOutput> getNetworkInterfaces() {
    return networkInterfaces;
  }

  public void setNetworkInterfaces(List<NetworkInterfaceForDescribeInstancesOutput> networkInterfaces) {
    this.networkInterfaces = networkInterfaces;
  }

  public InstanceForDescribeInstancesOutput osName(String osName) {
    this.osName = osName;
    return this;
  }

   /**
   * Get osName
   * @return osName
  **/
  @Schema(description = "")
  public String getOsName() {
    return osName;
  }

  public void setOsName(String osName) {
    this.osName = osName;
  }

  public InstanceForDescribeInstancesOutput osType(String osType) {
    this.osType = osType;
    return this;
  }

   /**
   * Get osType
   * @return osType
  **/
  @Schema(description = "")
  public String getOsType() {
    return osType;
  }

  public void setOsType(String osType) {
    this.osType = osType;
  }

  public InstanceForDescribeInstancesOutput projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @Schema(description = "")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public InstanceForDescribeInstancesOutput status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InstanceForDescribeInstancesOutput tags(List<TagForDescribeInstancesOutput> tags) {
    this.tags = tags;
    return this;
  }

  public InstanceForDescribeInstancesOutput addTagsItem(TagForDescribeInstancesOutput tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<TagForDescribeInstancesOutput>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @Valid
  @Schema(description = "")
  public List<TagForDescribeInstancesOutput> getTags() {
    return tags;
  }

  public void setTags(List<TagForDescribeInstancesOutput> tags) {
    this.tags = tags;
  }

  public InstanceForDescribeInstancesOutput volumes(List<VolumeForDescribeInstancesOutput> volumes) {
    this.volumes = volumes;
    return this;
  }

  public InstanceForDescribeInstancesOutput addVolumesItem(VolumeForDescribeInstancesOutput volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<VolumeForDescribeInstancesOutput>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Get volumes
   * @return volumes
  **/
  @Valid
  @Schema(description = "")
  public List<VolumeForDescribeInstancesOutput> getVolumes() {
    return volumes;
  }

  public void setVolumes(List<VolumeForDescribeInstancesOutput> volumes) {
    this.volumes = volumes;
  }

  public InstanceForDescribeInstancesOutput vpcId(String vpcId) {
    this.vpcId = vpcId;
    return this;
  }

   /**
   * Get vpcId
   * @return vpcId
  **/
  @Schema(description = "")
  public String getVpcId() {
    return vpcId;
  }

  public void setVpcId(String vpcId) {
    this.vpcId = vpcId;
  }

  public InstanceForDescribeInstancesOutput zoneId(String zoneId) {
    this.zoneId = zoneId;
    return this;
  }

   /**
   * Get zoneId
   * @return zoneId
  **/
  @Schema(description = "")
  public String getZoneId() {
    return zoneId;
  }

  public void setZoneId(String zoneId) {
    this.zoneId = zoneId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceForDescribeInstancesOutput instanceForDescribeInstancesOutput = (InstanceForDescribeInstancesOutput) o;
    return Objects.equals(this.cpus, instanceForDescribeInstancesOutput.cpus) &&
        Objects.equals(this.createdAt, instanceForDescribeInstancesOutput.createdAt) &&
        Objects.equals(this.imageId, instanceForDescribeInstancesOutput.imageId) &&
        Objects.equals(this.instanceChargeType, instanceForDescribeInstancesOutput.instanceChargeType) &&
        Objects.equals(this.instanceId, instanceForDescribeInstancesOutput.instanceId) &&
        Objects.equals(this.instanceName, instanceForDescribeInstancesOutput.instanceName) &&
        Objects.equals(this.instanceTypeId, instanceForDescribeInstancesOutput.instanceTypeId) &&
        Objects.equals(this.memorySize, instanceForDescribeInstancesOutput.memorySize) &&
        Objects.equals(this.networkInterfaces, instanceForDescribeInstancesOutput.networkInterfaces) &&
        Objects.equals(this.osName, instanceForDescribeInstancesOutput.osName) &&
        Objects.equals(this.osType, instanceForDescribeInstancesOutput.osType) &&
        Objects.equals(this.projectName, instanceForDescribeInstancesOutput.projectName) &&
        Objects.equals(this.status, instanceForDescribeInstancesOutput.status) &&
        Objects.equals(this.tags, instanceForDescribeInstancesOutput.tags) &&
        Objects.equals(this.volumes, instanceForDescribeInstancesOutput.volumes) &&
        Objects.equals(this.vpcId, instanceForDescribeInstancesOutput.vpcId) &&
        Objects.equals(this.zoneId, instanceForDescribeInstancesOutput.zoneId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpus, createdAt, imageId, instanceChargeType, instanceId, instanceName, instanceTypeId, memorySize, networkInterfaces, osName, osType, projectName, status, tags, volumes, vpcId, zoneId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceForDescribeInstancesOutput {\n");
    
    sb.append("    cpus: ").append(toIndentedString(cpus)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("    instanceChargeType: ").append(toIndentedString(instanceChargeType)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceName: ").append(toIndentedString(instanceName)).append("\n");
    sb.append("    instanceTypeId: ").append(toIndentedString(instanceTypeId)).append("\n");
    sb.append("    memorySize: ").append(toIndentedString(memorySize)).append("\n");
    sb.append("    networkInterfaces: ").append(toIndentedString(networkInterfaces)).append("\n");
    sb.append("    osName: ").append(toIndentedString(osName)).append("\n");
    sb.append("    osType: ").append(toIndentedString(osType)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    vpcId: ").append(toIndentedString(vpcId)).append("\n");
    sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
