/*
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ecs.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ecs.model.LaunchTemplateForDescribeLaunchTemplatesOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeLaunchTemplatesResponse
 */



public class DescribeLaunchTemplatesResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("LaunchTemplates")
  private List<LaunchTemplateForDescribeLaunchTemplatesOutput> launchTemplates = null;

  @SerializedName("NextToken")
  private String nextToken = null;

  public DescribeLaunchTemplatesResponse launchTemplates(List<LaunchTemplateForDescribeLaunchTemplatesOutput> launchTemplates) {
    this.launchTemplates = launchTemplates;
    return this;
  }

  public DescribeLaunchTemplatesResponse addLaunchTemplatesItem(LaunchTemplateForDescribeLaunchTemplatesOutput launchTemplatesItem) {
    if (this.launchTemplates == null) {
      this.launchTemplates = new ArrayList<LaunchTemplateForDescribeLaunchTemplatesOutput>();
    }
    this.launchTemplates.add(launchTemplatesItem);
    return this;
  }

   /**
   * Get launchTemplates
   * @return launchTemplates
  **/
  @Valid
  @Schema(description = "")
  public List<LaunchTemplateForDescribeLaunchTemplatesOutput> getLaunchTemplates() {
    return launchTemplates;
  }

  public void setLaunchTemplates(List<LaunchTemplateForDescribeLaunchTemplatesOutput> launchTemplates) {
    this.launchTemplates = launchTemplates;
  }

  public DescribeLaunchTemplatesResponse nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

   /**
   * Get nextToken
   * @return nextToken
  **/
  @Schema(description = "")
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeLaunchTemplatesResponse describeLaunchTemplatesResponse = (DescribeLaunchTemplatesResponse) o;
    return Objects.equals(this.launchTemplates, describeLaunchTemplatesResponse.launchTemplates) &&
        Objects.equals(this.nextToken, describeLaunchTemplatesResponse.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(launchTemplates, nextToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeLaunchTemplatesResponse {\n");
    
    sb.append("    launchTemplates: ").append(toIndentedString(launchTemplates)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
