/*
 * natgateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.natgateway.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateSessionLogRequest
 */



public class CreateSessionLogRequest {
  @SerializedName("Description")
  private String description = null;

  @SerializedName("EnableTlsTopicIndex")
  private Boolean enableTlsTopicIndex = null;

  @SerializedName("NatGatewayId")
  private String natGatewayId = null;

  @SerializedName("SessionLogName")
  private String sessionLogName = null;

  @SerializedName("TlsProjectName")
  private String tlsProjectName = null;

  @SerializedName("TlsTopicName")
  private String tlsTopicName = null;

  public CreateSessionLogRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateSessionLogRequest enableTlsTopicIndex(Boolean enableTlsTopicIndex) {
    this.enableTlsTopicIndex = enableTlsTopicIndex;
    return this;
  }

   /**
   * Get enableTlsTopicIndex
   * @return enableTlsTopicIndex
  **/
  @Schema(description = "")
  public Boolean isEnableTlsTopicIndex() {
    return enableTlsTopicIndex;
  }

  public void setEnableTlsTopicIndex(Boolean enableTlsTopicIndex) {
    this.enableTlsTopicIndex = enableTlsTopicIndex;
  }

  public CreateSessionLogRequest natGatewayId(String natGatewayId) {
    this.natGatewayId = natGatewayId;
    return this;
  }

   /**
   * Get natGatewayId
   * @return natGatewayId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getNatGatewayId() {
    return natGatewayId;
  }

  public void setNatGatewayId(String natGatewayId) {
    this.natGatewayId = natGatewayId;
  }

  public CreateSessionLogRequest sessionLogName(String sessionLogName) {
    this.sessionLogName = sessionLogName;
    return this;
  }

   /**
   * Get sessionLogName
   * @return sessionLogName
  **/
  @Schema(description = "")
  public String getSessionLogName() {
    return sessionLogName;
  }

  public void setSessionLogName(String sessionLogName) {
    this.sessionLogName = sessionLogName;
  }

  public CreateSessionLogRequest tlsProjectName(String tlsProjectName) {
    this.tlsProjectName = tlsProjectName;
    return this;
  }

   /**
   * Get tlsProjectName
   * @return tlsProjectName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTlsProjectName() {
    return tlsProjectName;
  }

  public void setTlsProjectName(String tlsProjectName) {
    this.tlsProjectName = tlsProjectName;
  }

  public CreateSessionLogRequest tlsTopicName(String tlsTopicName) {
    this.tlsTopicName = tlsTopicName;
    return this;
  }

   /**
   * Get tlsTopicName
   * @return tlsTopicName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTlsTopicName() {
    return tlsTopicName;
  }

  public void setTlsTopicName(String tlsTopicName) {
    this.tlsTopicName = tlsTopicName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSessionLogRequest createSessionLogRequest = (CreateSessionLogRequest) o;
    return Objects.equals(this.description, createSessionLogRequest.description) &&
        Objects.equals(this.enableTlsTopicIndex, createSessionLogRequest.enableTlsTopicIndex) &&
        Objects.equals(this.natGatewayId, createSessionLogRequest.natGatewayId) &&
        Objects.equals(this.sessionLogName, createSessionLogRequest.sessionLogName) &&
        Objects.equals(this.tlsProjectName, createSessionLogRequest.tlsProjectName) &&
        Objects.equals(this.tlsTopicName, createSessionLogRequest.tlsTopicName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, enableTlsTopicIndex, natGatewayId, sessionLogName, tlsProjectName, tlsTopicName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSessionLogRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enableTlsTopicIndex: ").append(toIndentedString(enableTlsTopicIndex)).append("\n");
    sb.append("    natGatewayId: ").append(toIndentedString(natGatewayId)).append("\n");
    sb.append("    sessionLogName: ").append(toIndentedString(sessionLogName)).append("\n");
    sb.append("    tlsProjectName: ").append(toIndentedString(tlsProjectName)).append("\n");
    sb.append("    tlsTopicName: ").append(toIndentedString(tlsTopicName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
