/*
 * natgateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.natgateway.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateSessionLogResponse
 */



public class CreateSessionLogResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("RequestId")
  private String requestId = null;

  @SerializedName("SessionLogId")
  private String sessionLogId = null;

  public CreateSessionLogResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @Schema(description = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public CreateSessionLogResponse sessionLogId(String sessionLogId) {
    this.sessionLogId = sessionLogId;
    return this;
  }

   /**
   * Get sessionLogId
   * @return sessionLogId
  **/
  @Schema(description = "")
  public String getSessionLogId() {
    return sessionLogId;
  }

  public void setSessionLogId(String sessionLogId) {
    this.sessionLogId = sessionLogId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSessionLogResponse createSessionLogResponse = (CreateSessionLogResponse) o;
    return Objects.equals(this.requestId, createSessionLogResponse.requestId) &&
        Objects.equals(this.sessionLogId, createSessionLogResponse.sessionLogId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, sessionLogId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSessionLogResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    sessionLogId: ").append(toIndentedString(sessionLogId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
