/*
 * natgateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.natgateway.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeSessionLogsRequest
 */



public class DescribeSessionLogsRequest {
  @SerializedName("NatGatewayId")
  private String natGatewayId = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("SessionLogIds")
  private List<String> sessionLogIds = null;

  @SerializedName("SessionLogName")
  private String sessionLogName = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("TlsProjectName")
  private String tlsProjectName = null;

  @SerializedName("TlsTopicName")
  private String tlsTopicName = null;

  public DescribeSessionLogsRequest natGatewayId(String natGatewayId) {
    this.natGatewayId = natGatewayId;
    return this;
  }

   /**
   * Get natGatewayId
   * @return natGatewayId
  **/
  @Schema(description = "")
  public String getNatGatewayId() {
    return natGatewayId;
  }

  public void setNatGatewayId(String natGatewayId) {
    this.natGatewayId = natGatewayId;
  }

  public DescribeSessionLogsRequest pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public DescribeSessionLogsRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public DescribeSessionLogsRequest sessionLogIds(List<String> sessionLogIds) {
    this.sessionLogIds = sessionLogIds;
    return this;
  }

  public DescribeSessionLogsRequest addSessionLogIdsItem(String sessionLogIdsItem) {
    if (this.sessionLogIds == null) {
      this.sessionLogIds = new ArrayList<String>();
    }
    this.sessionLogIds.add(sessionLogIdsItem);
    return this;
  }

   /**
   * Get sessionLogIds
   * @return sessionLogIds
  **/
  @Schema(description = "")
  public List<String> getSessionLogIds() {
    return sessionLogIds;
  }

  public void setSessionLogIds(List<String> sessionLogIds) {
    this.sessionLogIds = sessionLogIds;
  }

  public DescribeSessionLogsRequest sessionLogName(String sessionLogName) {
    this.sessionLogName = sessionLogName;
    return this;
  }

   /**
   * Get sessionLogName
   * @return sessionLogName
  **/
  @Schema(description = "")
  public String getSessionLogName() {
    return sessionLogName;
  }

  public void setSessionLogName(String sessionLogName) {
    this.sessionLogName = sessionLogName;
  }

  public DescribeSessionLogsRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public DescribeSessionLogsRequest tlsProjectName(String tlsProjectName) {
    this.tlsProjectName = tlsProjectName;
    return this;
  }

   /**
   * Get tlsProjectName
   * @return tlsProjectName
  **/
  @Schema(description = "")
  public String getTlsProjectName() {
    return tlsProjectName;
  }

  public void setTlsProjectName(String tlsProjectName) {
    this.tlsProjectName = tlsProjectName;
  }

  public DescribeSessionLogsRequest tlsTopicName(String tlsTopicName) {
    this.tlsTopicName = tlsTopicName;
    return this;
  }

   /**
   * Get tlsTopicName
   * @return tlsTopicName
  **/
  @Schema(description = "")
  public String getTlsTopicName() {
    return tlsTopicName;
  }

  public void setTlsTopicName(String tlsTopicName) {
    this.tlsTopicName = tlsTopicName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeSessionLogsRequest describeSessionLogsRequest = (DescribeSessionLogsRequest) o;
    return Objects.equals(this.natGatewayId, describeSessionLogsRequest.natGatewayId) &&
        Objects.equals(this.pageNumber, describeSessionLogsRequest.pageNumber) &&
        Objects.equals(this.pageSize, describeSessionLogsRequest.pageSize) &&
        Objects.equals(this.sessionLogIds, describeSessionLogsRequest.sessionLogIds) &&
        Objects.equals(this.sessionLogName, describeSessionLogsRequest.sessionLogName) &&
        Objects.equals(this.status, describeSessionLogsRequest.status) &&
        Objects.equals(this.tlsProjectName, describeSessionLogsRequest.tlsProjectName) &&
        Objects.equals(this.tlsTopicName, describeSessionLogsRequest.tlsTopicName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(natGatewayId, pageNumber, pageSize, sessionLogIds, sessionLogName, status, tlsProjectName, tlsTopicName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeSessionLogsRequest {\n");
    
    sb.append("    natGatewayId: ").append(toIndentedString(natGatewayId)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    sessionLogIds: ").append(toIndentedString(sessionLogIds)).append("\n");
    sb.append("    sessionLogName: ").append(toIndentedString(sessionLogName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tlsProjectName: ").append(toIndentedString(tlsProjectName)).append("\n");
    sb.append("    tlsTopicName: ").append(toIndentedString(tlsTopicName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
