/*
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.filenas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput
 */



public class AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput {
  @SerializedName("AutoSnapshotPolicyId")
  private String autoSnapshotPolicyId = null;

  @SerializedName("AutoSnapshotPolicyName")
  private String autoSnapshotPolicyName = null;

  @SerializedName("CreateTime")
  private String createTime = null;

  @SerializedName("FileSystemCount")
  private Integer fileSystemCount = null;

  @SerializedName("RepeatWeekdays")
  private String repeatWeekdays = null;

  @SerializedName("RetentionDays")
  private String retentionDays = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("TimePoints")
  private String timePoints = null;

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput autoSnapshotPolicyId(String autoSnapshotPolicyId) {
    this.autoSnapshotPolicyId = autoSnapshotPolicyId;
    return this;
  }

   /**
   * Get autoSnapshotPolicyId
   * @return autoSnapshotPolicyId
  **/
  @Schema(description = "")
  public String getAutoSnapshotPolicyId() {
    return autoSnapshotPolicyId;
  }

  public void setAutoSnapshotPolicyId(String autoSnapshotPolicyId) {
    this.autoSnapshotPolicyId = autoSnapshotPolicyId;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput autoSnapshotPolicyName(String autoSnapshotPolicyName) {
    this.autoSnapshotPolicyName = autoSnapshotPolicyName;
    return this;
  }

   /**
   * Get autoSnapshotPolicyName
   * @return autoSnapshotPolicyName
  **/
  @Schema(description = "")
  public String getAutoSnapshotPolicyName() {
    return autoSnapshotPolicyName;
  }

  public void setAutoSnapshotPolicyName(String autoSnapshotPolicyName) {
    this.autoSnapshotPolicyName = autoSnapshotPolicyName;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @Schema(description = "")
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput fileSystemCount(Integer fileSystemCount) {
    this.fileSystemCount = fileSystemCount;
    return this;
  }

   /**
   * Get fileSystemCount
   * @return fileSystemCount
  **/
  @Schema(description = "")
  public Integer getFileSystemCount() {
    return fileSystemCount;
  }

  public void setFileSystemCount(Integer fileSystemCount) {
    this.fileSystemCount = fileSystemCount;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput repeatWeekdays(String repeatWeekdays) {
    this.repeatWeekdays = repeatWeekdays;
    return this;
  }

   /**
   * Get repeatWeekdays
   * @return repeatWeekdays
  **/
  @Schema(description = "")
  public String getRepeatWeekdays() {
    return repeatWeekdays;
  }

  public void setRepeatWeekdays(String repeatWeekdays) {
    this.repeatWeekdays = repeatWeekdays;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput retentionDays(String retentionDays) {
    this.retentionDays = retentionDays;
    return this;
  }

   /**
   * Get retentionDays
   * @return retentionDays
  **/
  @Schema(description = "")
  public String getRetentionDays() {
    return retentionDays;
  }

  public void setRetentionDays(String retentionDays) {
    this.retentionDays = retentionDays;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput timePoints(String timePoints) {
    this.timePoints = timePoints;
    return this;
  }

   /**
   * Get timePoints
   * @return timePoints
  **/
  @Schema(description = "")
  public String getTimePoints() {
    return timePoints;
  }

  public void setTimePoints(String timePoints) {
    this.timePoints = timePoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput = (AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput) o;
    return Objects.equals(this.autoSnapshotPolicyId, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.autoSnapshotPolicyId) &&
        Objects.equals(this.autoSnapshotPolicyName, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.autoSnapshotPolicyName) &&
        Objects.equals(this.createTime, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.createTime) &&
        Objects.equals(this.fileSystemCount, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.fileSystemCount) &&
        Objects.equals(this.repeatWeekdays, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.repeatWeekdays) &&
        Objects.equals(this.retentionDays, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.retentionDays) &&
        Objects.equals(this.status, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.status) &&
        Objects.equals(this.timePoints, autoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput.timePoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoSnapshotPolicyId, autoSnapshotPolicyName, createTime, fileSystemCount, repeatWeekdays, retentionDays, status, timePoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoSnapshotPolicyForDescribeAutoSnapshotPoliciesOutput {\n");
    
    sb.append("    autoSnapshotPolicyId: ").append(toIndentedString(autoSnapshotPolicyId)).append("\n");
    sb.append("    autoSnapshotPolicyName: ").append(toIndentedString(autoSnapshotPolicyName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    fileSystemCount: ").append(toIndentedString(fileSystemCount)).append("\n");
    sb.append("    repeatWeekdays: ").append(toIndentedString(repeatWeekdays)).append("\n");
    sb.append("    retentionDays: ").append(toIndentedString(retentionDays)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timePoints: ").append(toIndentedString(timePoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
