/*
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.filenas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CancelAutoSnapshotPolicyRequest
 */



public class CancelAutoSnapshotPolicyRequest {
  @SerializedName("FileSystemIds")
  private String fileSystemIds = null;

  @SerializedName("SnapshotPolicyId")
  private String snapshotPolicyId = null;

  public CancelAutoSnapshotPolicyRequest fileSystemIds(String fileSystemIds) {
    this.fileSystemIds = fileSystemIds;
    return this;
  }

   /**
   * Get fileSystemIds
   * @return fileSystemIds
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getFileSystemIds() {
    return fileSystemIds;
  }

  public void setFileSystemIds(String fileSystemIds) {
    this.fileSystemIds = fileSystemIds;
  }

  public CancelAutoSnapshotPolicyRequest snapshotPolicyId(String snapshotPolicyId) {
    this.snapshotPolicyId = snapshotPolicyId;
    return this;
  }

   /**
   * Get snapshotPolicyId
   * @return snapshotPolicyId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getSnapshotPolicyId() {
    return snapshotPolicyId;
  }

  public void setSnapshotPolicyId(String snapshotPolicyId) {
    this.snapshotPolicyId = snapshotPolicyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelAutoSnapshotPolicyRequest cancelAutoSnapshotPolicyRequest = (CancelAutoSnapshotPolicyRequest) o;
    return Objects.equals(this.fileSystemIds, cancelAutoSnapshotPolicyRequest.fileSystemIds) &&
        Objects.equals(this.snapshotPolicyId, cancelAutoSnapshotPolicyRequest.snapshotPolicyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileSystemIds, snapshotPolicyId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelAutoSnapshotPolicyRequest {\n");
    
    sb.append("    fileSystemIds: ").append(toIndentedString(fileSystemIds)).append("\n");
    sb.append("    snapshotPolicyId: ").append(toIndentedString(snapshotPolicyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
