/*
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.filenas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateAutoSnapshotPolicyRequest
 */



public class CreateAutoSnapshotPolicyRequest {
  @SerializedName("AutoSnapshotPolicyName")
  private String autoSnapshotPolicyName = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("RepeatWeekdays")
  private String repeatWeekdays = null;

  @SerializedName("RetentionDays")
  private String retentionDays = null;

  @SerializedName("SnapshotPolicyName")
  private String snapshotPolicyName = null;

  @SerializedName("TimePoints")
  private String timePoints = null;

  public CreateAutoSnapshotPolicyRequest autoSnapshotPolicyName(String autoSnapshotPolicyName) {
    this.autoSnapshotPolicyName = autoSnapshotPolicyName;
    return this;
  }

   /**
   * Get autoSnapshotPolicyName
   * @return autoSnapshotPolicyName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getAutoSnapshotPolicyName() {
    return autoSnapshotPolicyName;
  }

  public void setAutoSnapshotPolicyName(String autoSnapshotPolicyName) {
    this.autoSnapshotPolicyName = autoSnapshotPolicyName;
  }

  public CreateAutoSnapshotPolicyRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateAutoSnapshotPolicyRequest repeatWeekdays(String repeatWeekdays) {
    this.repeatWeekdays = repeatWeekdays;
    return this;
  }

   /**
   * Get repeatWeekdays
   * @return repeatWeekdays
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getRepeatWeekdays() {
    return repeatWeekdays;
  }

  public void setRepeatWeekdays(String repeatWeekdays) {
    this.repeatWeekdays = repeatWeekdays;
  }

  public CreateAutoSnapshotPolicyRequest retentionDays(String retentionDays) {
    this.retentionDays = retentionDays;
    return this;
  }

   /**
   * Get retentionDays
   * @return retentionDays
  **/
  @Schema(description = "")
  public String getRetentionDays() {
    return retentionDays;
  }

  public void setRetentionDays(String retentionDays) {
    this.retentionDays = retentionDays;
  }

  public CreateAutoSnapshotPolicyRequest snapshotPolicyName(String snapshotPolicyName) {
    this.snapshotPolicyName = snapshotPolicyName;
    return this;
  }

   /**
   * Get snapshotPolicyName
   * @return snapshotPolicyName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getSnapshotPolicyName() {
    return snapshotPolicyName;
  }

  public void setSnapshotPolicyName(String snapshotPolicyName) {
    this.snapshotPolicyName = snapshotPolicyName;
  }

  public CreateAutoSnapshotPolicyRequest timePoints(String timePoints) {
    this.timePoints = timePoints;
    return this;
  }

   /**
   * Get timePoints
   * @return timePoints
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTimePoints() {
    return timePoints;
  }

  public void setTimePoints(String timePoints) {
    this.timePoints = timePoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAutoSnapshotPolicyRequest createAutoSnapshotPolicyRequest = (CreateAutoSnapshotPolicyRequest) o;
    return Objects.equals(this.autoSnapshotPolicyName, createAutoSnapshotPolicyRequest.autoSnapshotPolicyName) &&
        Objects.equals(this.description, createAutoSnapshotPolicyRequest.description) &&
        Objects.equals(this.repeatWeekdays, createAutoSnapshotPolicyRequest.repeatWeekdays) &&
        Objects.equals(this.retentionDays, createAutoSnapshotPolicyRequest.retentionDays) &&
        Objects.equals(this.snapshotPolicyName, createAutoSnapshotPolicyRequest.snapshotPolicyName) &&
        Objects.equals(this.timePoints, createAutoSnapshotPolicyRequest.timePoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoSnapshotPolicyName, description, repeatWeekdays, retentionDays, snapshotPolicyName, timePoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAutoSnapshotPolicyRequest {\n");
    
    sb.append("    autoSnapshotPolicyName: ").append(toIndentedString(autoSnapshotPolicyName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    repeatWeekdays: ").append(toIndentedString(repeatWeekdays)).append("\n");
    sb.append("    retentionDays: ").append(toIndentedString(retentionDays)).append("\n");
    sb.append("    snapshotPolicyName: ").append(toIndentedString(snapshotPolicyName)).append("\n");
    sb.append("    timePoints: ").append(toIndentedString(timePoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
