/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.ModelUsageForBotsChatCompletionsOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * BotUsageForBotsChatCompletionsOutput
 */



public class BotUsageForBotsChatCompletionsOutput {
  @SerializedName("model_usage")
  private List<ModelUsageForBotsChatCompletionsOutput> modelUsage = null;

  public BotUsageForBotsChatCompletionsOutput modelUsage(List<ModelUsageForBotsChatCompletionsOutput> modelUsage) {
    this.modelUsage = modelUsage;
    return this;
  }

  public BotUsageForBotsChatCompletionsOutput addModelUsageItem(ModelUsageForBotsChatCompletionsOutput modelUsageItem) {
    if (this.modelUsage == null) {
      this.modelUsage = new ArrayList<ModelUsageForBotsChatCompletionsOutput>();
    }
    this.modelUsage.add(modelUsageItem);
    return this;
  }

   /**
   * Get modelUsage
   * @return modelUsage
  **/
  @Valid
  @Schema(description = "")
  public List<ModelUsageForBotsChatCompletionsOutput> getModelUsage() {
    return modelUsage;
  }

  public void setModelUsage(List<ModelUsageForBotsChatCompletionsOutput> modelUsage) {
    this.modelUsage = modelUsage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BotUsageForBotsChatCompletionsOutput botUsageForBotsChatCompletionsOutput = (BotUsageForBotsChatCompletionsOutput) o;
    return Objects.equals(this.modelUsage, botUsageForBotsChatCompletionsOutput.modelUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelUsage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BotUsageForBotsChatCompletionsOutput {\n");
    
    sb.append("    modelUsage: ").append(toIndentedString(modelUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
