/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.ChoiceForChatCompletionsVisionOutput;
import com.byteplus.ark.model.UsageForChatCompletionsVisionOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ChatCompletionsVisionResponse
 */



public class ChatCompletionsVisionResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("choices")
  private List<ChoiceForChatCompletionsVisionOutput> choices = null;

  @SerializedName("created")
  private Integer created = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("object")
  private String object = null;

  @SerializedName("usage")
  private UsageForChatCompletionsVisionOutput usage = null;

  public ChatCompletionsVisionResponse choices(List<ChoiceForChatCompletionsVisionOutput> choices) {
    this.choices = choices;
    return this;
  }

  public ChatCompletionsVisionResponse addChoicesItem(ChoiceForChatCompletionsVisionOutput choicesItem) {
    if (this.choices == null) {
      this.choices = new ArrayList<ChoiceForChatCompletionsVisionOutput>();
    }
    this.choices.add(choicesItem);
    return this;
  }

   /**
   * Get choices
   * @return choices
  **/
  @Valid
  @Schema(description = "")
  public List<ChoiceForChatCompletionsVisionOutput> getChoices() {
    return choices;
  }

  public void setChoices(List<ChoiceForChatCompletionsVisionOutput> choices) {
    this.choices = choices;
  }

  public ChatCompletionsVisionResponse created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public ChatCompletionsVisionResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ChatCompletionsVisionResponse model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public ChatCompletionsVisionResponse object(String object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @Schema(description = "")
  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  public ChatCompletionsVisionResponse usage(UsageForChatCompletionsVisionOutput usage) {
    this.usage = usage;
    return this;
  }

   /**
   * Get usage
   * @return usage
  **/
  @Valid
  @Schema(description = "")
  public UsageForChatCompletionsVisionOutput getUsage() {
    return usage;
  }

  public void setUsage(UsageForChatCompletionsVisionOutput usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionsVisionResponse chatCompletionsVisionResponse = (ChatCompletionsVisionResponse) o;
    return Objects.equals(this.choices, chatCompletionsVisionResponse.choices) &&
        Objects.equals(this.created, chatCompletionsVisionResponse.created) &&
        Objects.equals(this.id, chatCompletionsVisionResponse.id) &&
        Objects.equals(this.model, chatCompletionsVisionResponse.model) &&
        Objects.equals(this.object, chatCompletionsVisionResponse.object) &&
        Objects.equals(this.usage, chatCompletionsVisionResponse.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(choices, created, id, model, object, usage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionsVisionResponse {\n");
    
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
