/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.LogitBiasForChatCompletionsVisionInput;
import com.byteplus.ark.model.MessagesForChatCompletionsVisionInput;
import com.byteplus.ark.model.StreamOptionsForChatCompletionsVisionInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ChatCompletionsVisionRequest
 */



public class ChatCompletionsVisionRequest {
  @SerializedName("logit_bias")
  private LogitBiasForChatCompletionsVisionInput logitBias = null;

  @SerializedName("logprobs")
  private Boolean logprobs = null;

  @SerializedName("max_tokens")
  private Integer maxTokens = null;

  @SerializedName("messages")
  private MessagesForChatCompletionsVisionInput messages = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("stop")
  private List<String> stop = null;

  @SerializedName("stream")
  private Boolean stream = null;

  @SerializedName("stream_options")
  private StreamOptionsForChatCompletionsVisionInput streamOptions = null;

  @SerializedName("temperature")
  private Float temperature = null;

  @SerializedName("top_logprobs")
  private Integer topLogprobs = null;

  @SerializedName("top_p")
  private Float topP = null;

  public ChatCompletionsVisionRequest logitBias(LogitBiasForChatCompletionsVisionInput logitBias) {
    this.logitBias = logitBias;
    return this;
  }

   /**
   * Get logitBias
   * @return logitBias
  **/
  @Valid
  @Schema(description = "")
  public LogitBiasForChatCompletionsVisionInput getLogitBias() {
    return logitBias;
  }

  public void setLogitBias(LogitBiasForChatCompletionsVisionInput logitBias) {
    this.logitBias = logitBias;
  }

  public ChatCompletionsVisionRequest logprobs(Boolean logprobs) {
    this.logprobs = logprobs;
    return this;
  }

   /**
   * Get logprobs
   * @return logprobs
  **/
  @Schema(description = "")
  public Boolean isLogprobs() {
    return logprobs;
  }

  public void setLogprobs(Boolean logprobs) {
    this.logprobs = logprobs;
  }

  public ChatCompletionsVisionRequest maxTokens(Integer maxTokens) {
    this.maxTokens = maxTokens;
    return this;
  }

   /**
   * Get maxTokens
   * @return maxTokens
  **/
  @Schema(description = "")
  public Integer getMaxTokens() {
    return maxTokens;
  }

  public void setMaxTokens(Integer maxTokens) {
    this.maxTokens = maxTokens;
  }

  public ChatCompletionsVisionRequest messages(MessagesForChatCompletionsVisionInput messages) {
    this.messages = messages;
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Valid
  @Schema(description = "")
  public MessagesForChatCompletionsVisionInput getMessages() {
    return messages;
  }

  public void setMessages(MessagesForChatCompletionsVisionInput messages) {
    this.messages = messages;
  }

  public ChatCompletionsVisionRequest model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public ChatCompletionsVisionRequest stop(List<String> stop) {
    this.stop = stop;
    return this;
  }

  public ChatCompletionsVisionRequest addStopItem(String stopItem) {
    if (this.stop == null) {
      this.stop = new ArrayList<String>();
    }
    this.stop.add(stopItem);
    return this;
  }

   /**
   * Get stop
   * @return stop
  **/
  @Schema(description = "")
  public List<String> getStop() {
    return stop;
  }

  public void setStop(List<String> stop) {
    this.stop = stop;
  }

  public ChatCompletionsVisionRequest stream(Boolean stream) {
    this.stream = stream;
    return this;
  }

   /**
   * Get stream
   * @return stream
  **/
  @Schema(description = "")
  public Boolean isStream() {
    return stream;
  }

  public void setStream(Boolean stream) {
    this.stream = stream;
  }

  public ChatCompletionsVisionRequest streamOptions(StreamOptionsForChatCompletionsVisionInput streamOptions) {
    this.streamOptions = streamOptions;
    return this;
  }

   /**
   * Get streamOptions
   * @return streamOptions
  **/
  @Valid
  @Schema(description = "")
  public StreamOptionsForChatCompletionsVisionInput getStreamOptions() {
    return streamOptions;
  }

  public void setStreamOptions(StreamOptionsForChatCompletionsVisionInput streamOptions) {
    this.streamOptions = streamOptions;
  }

  public ChatCompletionsVisionRequest temperature(Float temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * Get temperature
   * @return temperature
  **/
  @Schema(description = "")
  public Float getTemperature() {
    return temperature;
  }

  public void setTemperature(Float temperature) {
    this.temperature = temperature;
  }

  public ChatCompletionsVisionRequest topLogprobs(Integer topLogprobs) {
    this.topLogprobs = topLogprobs;
    return this;
  }

   /**
   * Get topLogprobs
   * @return topLogprobs
  **/
  @Schema(description = "")
  public Integer getTopLogprobs() {
    return topLogprobs;
  }

  public void setTopLogprobs(Integer topLogprobs) {
    this.topLogprobs = topLogprobs;
  }

  public ChatCompletionsVisionRequest topP(Float topP) {
    this.topP = topP;
    return this;
  }

   /**
   * Get topP
   * @return topP
  **/
  @Schema(description = "")
  public Float getTopP() {
    return topP;
  }

  public void setTopP(Float topP) {
    this.topP = topP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionsVisionRequest chatCompletionsVisionRequest = (ChatCompletionsVisionRequest) o;
    return Objects.equals(this.logitBias, chatCompletionsVisionRequest.logitBias) &&
        Objects.equals(this.logprobs, chatCompletionsVisionRequest.logprobs) &&
        Objects.equals(this.maxTokens, chatCompletionsVisionRequest.maxTokens) &&
        Objects.equals(this.messages, chatCompletionsVisionRequest.messages) &&
        Objects.equals(this.model, chatCompletionsVisionRequest.model) &&
        Objects.equals(this.stop, chatCompletionsVisionRequest.stop) &&
        Objects.equals(this.stream, chatCompletionsVisionRequest.stream) &&
        Objects.equals(this.streamOptions, chatCompletionsVisionRequest.streamOptions) &&
        Objects.equals(this.temperature, chatCompletionsVisionRequest.temperature) &&
        Objects.equals(this.topLogprobs, chatCompletionsVisionRequest.topLogprobs) &&
        Objects.equals(this.topP, chatCompletionsVisionRequest.topP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logitBias, logprobs, maxTokens, messages, model, stop, stream, streamOptions, temperature, topLogprobs, topP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionsVisionRequest {\n");
    
    sb.append("    logitBias: ").append(toIndentedString(logitBias)).append("\n");
    sb.append("    logprobs: ").append(toIndentedString(logprobs)).append("\n");
    sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    streamOptions: ").append(toIndentedString(streamOptions)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topLogprobs: ").append(toIndentedString(topLogprobs)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
