/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.DeltaForBatchChatCompletionsOutput;
import com.byteplus.ark.model.LogprobsForBatchChatCompletionsOutput;
import com.byteplus.ark.model.MessageForBatchChatCompletionsOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ChoiceForBatchChatCompletionsOutput
 */



public class ChoiceForBatchChatCompletionsOutput {
  @SerializedName("delta")
  private DeltaForBatchChatCompletionsOutput delta = null;

  @SerializedName("finish_reason")
  private String finishReason = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("logprobs")
  private LogprobsForBatchChatCompletionsOutput logprobs = null;

  @SerializedName("message")
  private MessageForBatchChatCompletionsOutput message = null;

  public ChoiceForBatchChatCompletionsOutput delta(DeltaForBatchChatCompletionsOutput delta) {
    this.delta = delta;
    return this;
  }

   /**
   * Get delta
   * @return delta
  **/
  @Valid
  @Schema(description = "")
  public DeltaForBatchChatCompletionsOutput getDelta() {
    return delta;
  }

  public void setDelta(DeltaForBatchChatCompletionsOutput delta) {
    this.delta = delta;
  }

  public ChoiceForBatchChatCompletionsOutput finishReason(String finishReason) {
    this.finishReason = finishReason;
    return this;
  }

   /**
   * Get finishReason
   * @return finishReason
  **/
  @Schema(description = "")
  public String getFinishReason() {
    return finishReason;
  }

  public void setFinishReason(String finishReason) {
    this.finishReason = finishReason;
  }

  public ChoiceForBatchChatCompletionsOutput index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @Schema(description = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public ChoiceForBatchChatCompletionsOutput logprobs(LogprobsForBatchChatCompletionsOutput logprobs) {
    this.logprobs = logprobs;
    return this;
  }

   /**
   * Get logprobs
   * @return logprobs
  **/
  @Valid
  @Schema(description = "")
  public LogprobsForBatchChatCompletionsOutput getLogprobs() {
    return logprobs;
  }

  public void setLogprobs(LogprobsForBatchChatCompletionsOutput logprobs) {
    this.logprobs = logprobs;
  }

  public ChoiceForBatchChatCompletionsOutput message(MessageForBatchChatCompletionsOutput message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Valid
  @Schema(description = "")
  public MessageForBatchChatCompletionsOutput getMessage() {
    return message;
  }

  public void setMessage(MessageForBatchChatCompletionsOutput message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChoiceForBatchChatCompletionsOutput choiceForBatchChatCompletionsOutput = (ChoiceForBatchChatCompletionsOutput) o;
    return Objects.equals(this.delta, choiceForBatchChatCompletionsOutput.delta) &&
        Objects.equals(this.finishReason, choiceForBatchChatCompletionsOutput.finishReason) &&
        Objects.equals(this.index, choiceForBatchChatCompletionsOutput.index) &&
        Objects.equals(this.logprobs, choiceForBatchChatCompletionsOutput.logprobs) &&
        Objects.equals(this.message, choiceForBatchChatCompletionsOutput.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delta, finishReason, index, logprobs, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChoiceForBatchChatCompletionsOutput {\n");
    
    sb.append("    delta: ").append(toIndentedString(delta)).append("\n");
    sb.append("    finishReason: ").append(toIndentedString(finishReason)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    logprobs: ").append(toIndentedString(logprobs)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
