/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.DataForEmbeddingsMultimodalOutput;
import com.byteplus.ark.model.UsageForEmbeddingsMultimodalOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * EmbeddingsMultimodalResponse
 */



public class EmbeddingsMultimodalResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("created")
  private Integer created = null;

  @SerializedName("data")
  private DataForEmbeddingsMultimodalOutput data = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("object")
  private String object = null;

  @SerializedName("usage")
  private UsageForEmbeddingsMultimodalOutput usage = null;

  public EmbeddingsMultimodalResponse created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public EmbeddingsMultimodalResponse data(DataForEmbeddingsMultimodalOutput data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Valid
  @Schema(description = "")
  public DataForEmbeddingsMultimodalOutput getData() {
    return data;
  }

  public void setData(DataForEmbeddingsMultimodalOutput data) {
    this.data = data;
  }

  public EmbeddingsMultimodalResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EmbeddingsMultimodalResponse model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public EmbeddingsMultimodalResponse object(String object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @Schema(description = "")
  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  public EmbeddingsMultimodalResponse usage(UsageForEmbeddingsMultimodalOutput usage) {
    this.usage = usage;
    return this;
  }

   /**
   * Get usage
   * @return usage
  **/
  @Valid
  @Schema(description = "")
  public UsageForEmbeddingsMultimodalOutput getUsage() {
    return usage;
  }

  public void setUsage(UsageForEmbeddingsMultimodalOutput usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddingsMultimodalResponse embeddingsMultimodalResponse = (EmbeddingsMultimodalResponse) o;
    return Objects.equals(this.created, embeddingsMultimodalResponse.created) &&
        Objects.equals(this.data, embeddingsMultimodalResponse.data) &&
        Objects.equals(this.id, embeddingsMultimodalResponse.id) &&
        Objects.equals(this.model, embeddingsMultimodalResponse.model) &&
        Objects.equals(this.object, embeddingsMultimodalResponse.object) &&
        Objects.equals(this.usage, embeddingsMultimodalResponse.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, data, id, model, object, usage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddingsMultimodalResponse {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
