/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ModelUsageForBotsChatCompletionsOutput
 */



public class ModelUsageForBotsChatCompletionsOutput {
  @SerializedName("completion_tokens")
  private Integer completionTokens = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("prompt_tokens")
  private Integer promptTokens = null;

  @SerializedName("total_tokens")
  private Integer totalTokens = null;

  public ModelUsageForBotsChatCompletionsOutput completionTokens(Integer completionTokens) {
    this.completionTokens = completionTokens;
    return this;
  }

   /**
   * Get completionTokens
   * @return completionTokens
  **/
  @Schema(description = "")
  public Integer getCompletionTokens() {
    return completionTokens;
  }

  public void setCompletionTokens(Integer completionTokens) {
    this.completionTokens = completionTokens;
  }

  public ModelUsageForBotsChatCompletionsOutput name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelUsageForBotsChatCompletionsOutput promptTokens(Integer promptTokens) {
    this.promptTokens = promptTokens;
    return this;
  }

   /**
   * Get promptTokens
   * @return promptTokens
  **/
  @Schema(description = "")
  public Integer getPromptTokens() {
    return promptTokens;
  }

  public void setPromptTokens(Integer promptTokens) {
    this.promptTokens = promptTokens;
  }

  public ModelUsageForBotsChatCompletionsOutput totalTokens(Integer totalTokens) {
    this.totalTokens = totalTokens;
    return this;
  }

   /**
   * Get totalTokens
   * @return totalTokens
  **/
  @Schema(description = "")
  public Integer getTotalTokens() {
    return totalTokens;
  }

  public void setTotalTokens(Integer totalTokens) {
    this.totalTokens = totalTokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelUsageForBotsChatCompletionsOutput modelUsageForBotsChatCompletionsOutput = (ModelUsageForBotsChatCompletionsOutput) o;
    return Objects.equals(this.completionTokens, modelUsageForBotsChatCompletionsOutput.completionTokens) &&
        Objects.equals(this.name, modelUsageForBotsChatCompletionsOutput.name) &&
        Objects.equals(this.promptTokens, modelUsageForBotsChatCompletionsOutput.promptTokens) &&
        Objects.equals(this.totalTokens, modelUsageForBotsChatCompletionsOutput.totalTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completionTokens, name, promptTokens, totalTokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelUsageForBotsChatCompletionsOutput {\n");
    
    sb.append("    completionTokens: ").append(toIndentedString(completionTokens)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    promptTokens: ").append(toIndentedString(promptTokens)).append("\n");
    sb.append("    totalTokens: ").append(toIndentedString(totalTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
