/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * PromptTokensDetailsForEmbeddingsMultimodalOutput
 */



public class PromptTokensDetailsForEmbeddingsMultimodalOutput {
  @SerializedName("image_tokens")
  private Integer imageTokens = null;

  @SerializedName("text_tokens")
  private Integer textTokens = null;

  public PromptTokensDetailsForEmbeddingsMultimodalOutput imageTokens(Integer imageTokens) {
    this.imageTokens = imageTokens;
    return this;
  }

   /**
   * Get imageTokens
   * @return imageTokens
  **/
  @Schema(description = "")
  public Integer getImageTokens() {
    return imageTokens;
  }

  public void setImageTokens(Integer imageTokens) {
    this.imageTokens = imageTokens;
  }

  public PromptTokensDetailsForEmbeddingsMultimodalOutput textTokens(Integer textTokens) {
    this.textTokens = textTokens;
    return this;
  }

   /**
   * Get textTokens
   * @return textTokens
  **/
  @Schema(description = "")
  public Integer getTextTokens() {
    return textTokens;
  }

  public void setTextTokens(Integer textTokens) {
    this.textTokens = textTokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptTokensDetailsForEmbeddingsMultimodalOutput promptTokensDetailsForEmbeddingsMultimodalOutput = (PromptTokensDetailsForEmbeddingsMultimodalOutput) o;
    return Objects.equals(this.imageTokens, promptTokensDetailsForEmbeddingsMultimodalOutput.imageTokens) &&
        Objects.equals(this.textTokens, promptTokensDetailsForEmbeddingsMultimodalOutput.textTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageTokens, textTokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptTokensDetailsForEmbeddingsMultimodalOutput {\n");
    
    sb.append("    imageTokens: ").append(toIndentedString(imageTokens)).append("\n");
    sb.append("    textTokens: ").append(toIndentedString(textTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
