/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * TokenizationRequest
 */



public class TokenizationRequest {
  @SerializedName("model")
  private String model = null;

  @SerializedName("text")
  private List<String> text = null;

  public TokenizationRequest model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public TokenizationRequest text(List<String> text) {
    this.text = text;
    return this;
  }

  public TokenizationRequest addTextItem(String textItem) {
    if (this.text == null) {
      this.text = new ArrayList<String>();
    }
    this.text.add(textItem);
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @Schema(description = "")
  public List<String> getText() {
    return text;
  }

  public void setText(List<String> text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenizationRequest tokenizationRequest = (TokenizationRequest) o;
    return Objects.equals(this.model, tokenizationRequest.model) &&
        Objects.equals(this.text, tokenizationRequest.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenizationRequest {\n");
    
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
