/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.ConvertfunctionForBatchChatCompletionsInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ToolForBatchChatCompletionsInput
 */



public class ToolForBatchChatCompletionsInput {
  @SerializedName("function")
  private ConvertfunctionForBatchChatCompletionsInput function = null;

  @SerializedName("type")
  private String type = null;

  public ToolForBatchChatCompletionsInput function(ConvertfunctionForBatchChatCompletionsInput function) {
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @Valid
  @Schema(description = "")
  public ConvertfunctionForBatchChatCompletionsInput getFunction() {
    return function;
  }

  public void setFunction(ConvertfunctionForBatchChatCompletionsInput function) {
    this.function = function;
  }

  public ToolForBatchChatCompletionsInput type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolForBatchChatCompletionsInput toolForBatchChatCompletionsInput = (ToolForBatchChatCompletionsInput) o;
    return Objects.equals(this.function, toolForBatchChatCompletionsInput.function) &&
        Objects.equals(this.type, toolForBatchChatCompletionsInput.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(function, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolForBatchChatCompletionsInput {\n");
    
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
