/*
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.ark.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.ark.model.FunctionForBatchChatCompletionsOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ToolCallForBatchChatCompletionsOutput
 */



public class ToolCallForBatchChatCompletionsOutput {
  @SerializedName("function")
  private FunctionForBatchChatCompletionsOutput function = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("type")
  private String type = null;

  public ToolCallForBatchChatCompletionsOutput function(FunctionForBatchChatCompletionsOutput function) {
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @Valid
  @Schema(description = "")
  public FunctionForBatchChatCompletionsOutput getFunction() {
    return function;
  }

  public void setFunction(FunctionForBatchChatCompletionsOutput function) {
    this.function = function;
  }

  public ToolCallForBatchChatCompletionsOutput id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ToolCallForBatchChatCompletionsOutput index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @Schema(description = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public ToolCallForBatchChatCompletionsOutput type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolCallForBatchChatCompletionsOutput toolCallForBatchChatCompletionsOutput = (ToolCallForBatchChatCompletionsOutput) o;
    return Objects.equals(this.function, toolCallForBatchChatCompletionsOutput.function) &&
        Objects.equals(this.id, toolCallForBatchChatCompletionsOutput.id) &&
        Objects.equals(this.index, toolCallForBatchChatCompletionsOutput.index) &&
        Objects.equals(this.type, toolCallForBatchChatCompletionsOutput.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(function, id, index, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolCallForBatchChatCompletionsOutput {\n");
    
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
