/*
 * vedbm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.vedbm.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.vedbm.model.AddressForDescribeDBEndpointOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * EndpointForDescribeDBEndpointOutput
 */



public class EndpointForDescribeDBEndpointOutput {
  @SerializedName("Addresses")
  private List<AddressForDescribeDBEndpointOutput> addresses = null;

  @SerializedName("AutoAddNewNodes")
  private Boolean autoAddNewNodes = null;

  @SerializedName("ConnectionPool")
  private String connectionPool = null;

  @SerializedName("ConsistLevel")
  private String consistLevel = null;

  @SerializedName("ConsistTimeout")
  private Integer consistTimeout = null;

  @SerializedName("ConsistTimeoutAction")
  private String consistTimeoutAction = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("DistributedTransaction")
  private Boolean distributedTransaction = null;

  @SerializedName("EndpointId")
  private String endpointId = null;

  @SerializedName("EndpointName")
  private String endpointName = null;

  @SerializedName("EndpointType")
  private String endpointType = null;

  @SerializedName("MasterAcceptReadRequests")
  private Boolean masterAcceptReadRequests = null;

  @SerializedName("NodeIds")
  private List<String> nodeIds = null;

  @SerializedName("ReadWriteMode")
  private String readWriteMode = null;

  public EndpointForDescribeDBEndpointOutput addresses(List<AddressForDescribeDBEndpointOutput> addresses) {
    this.addresses = addresses;
    return this;
  }

  public EndpointForDescribeDBEndpointOutput addAddressesItem(AddressForDescribeDBEndpointOutput addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<AddressForDescribeDBEndpointOutput>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Get addresses
   * @return addresses
  **/
  @Valid
  @Schema(description = "")
  public List<AddressForDescribeDBEndpointOutput> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<AddressForDescribeDBEndpointOutput> addresses) {
    this.addresses = addresses;
  }

  public EndpointForDescribeDBEndpointOutput autoAddNewNodes(Boolean autoAddNewNodes) {
    this.autoAddNewNodes = autoAddNewNodes;
    return this;
  }

   /**
   * Get autoAddNewNodes
   * @return autoAddNewNodes
  **/
  @Schema(description = "")
  public Boolean isAutoAddNewNodes() {
    return autoAddNewNodes;
  }

  public void setAutoAddNewNodes(Boolean autoAddNewNodes) {
    this.autoAddNewNodes = autoAddNewNodes;
  }

  public EndpointForDescribeDBEndpointOutput connectionPool(String connectionPool) {
    this.connectionPool = connectionPool;
    return this;
  }

   /**
   * Get connectionPool
   * @return connectionPool
  **/
  @Schema(description = "")
  public String getConnectionPool() {
    return connectionPool;
  }

  public void setConnectionPool(String connectionPool) {
    this.connectionPool = connectionPool;
  }

  public EndpointForDescribeDBEndpointOutput consistLevel(String consistLevel) {
    this.consistLevel = consistLevel;
    return this;
  }

   /**
   * Get consistLevel
   * @return consistLevel
  **/
  @Schema(description = "")
  public String getConsistLevel() {
    return consistLevel;
  }

  public void setConsistLevel(String consistLevel) {
    this.consistLevel = consistLevel;
  }

  public EndpointForDescribeDBEndpointOutput consistTimeout(Integer consistTimeout) {
    this.consistTimeout = consistTimeout;
    return this;
  }

   /**
   * Get consistTimeout
   * @return consistTimeout
  **/
  @Schema(description = "")
  public Integer getConsistTimeout() {
    return consistTimeout;
  }

  public void setConsistTimeout(Integer consistTimeout) {
    this.consistTimeout = consistTimeout;
  }

  public EndpointForDescribeDBEndpointOutput consistTimeoutAction(String consistTimeoutAction) {
    this.consistTimeoutAction = consistTimeoutAction;
    return this;
  }

   /**
   * Get consistTimeoutAction
   * @return consistTimeoutAction
  **/
  @Schema(description = "")
  public String getConsistTimeoutAction() {
    return consistTimeoutAction;
  }

  public void setConsistTimeoutAction(String consistTimeoutAction) {
    this.consistTimeoutAction = consistTimeoutAction;
  }

  public EndpointForDescribeDBEndpointOutput description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EndpointForDescribeDBEndpointOutput distributedTransaction(Boolean distributedTransaction) {
    this.distributedTransaction = distributedTransaction;
    return this;
  }

   /**
   * Get distributedTransaction
   * @return distributedTransaction
  **/
  @Schema(description = "")
  public Boolean isDistributedTransaction() {
    return distributedTransaction;
  }

  public void setDistributedTransaction(Boolean distributedTransaction) {
    this.distributedTransaction = distributedTransaction;
  }

  public EndpointForDescribeDBEndpointOutput endpointId(String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Get endpointId
   * @return endpointId
  **/
  @Schema(description = "")
  public String getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(String endpointId) {
    this.endpointId = endpointId;
  }

  public EndpointForDescribeDBEndpointOutput endpointName(String endpointName) {
    this.endpointName = endpointName;
    return this;
  }

   /**
   * Get endpointName
   * @return endpointName
  **/
  @Schema(description = "")
  public String getEndpointName() {
    return endpointName;
  }

  public void setEndpointName(String endpointName) {
    this.endpointName = endpointName;
  }

  public EndpointForDescribeDBEndpointOutput endpointType(String endpointType) {
    this.endpointType = endpointType;
    return this;
  }

   /**
   * Get endpointType
   * @return endpointType
  **/
  @Schema(description = "")
  public String getEndpointType() {
    return endpointType;
  }

  public void setEndpointType(String endpointType) {
    this.endpointType = endpointType;
  }

  public EndpointForDescribeDBEndpointOutput masterAcceptReadRequests(Boolean masterAcceptReadRequests) {
    this.masterAcceptReadRequests = masterAcceptReadRequests;
    return this;
  }

   /**
   * Get masterAcceptReadRequests
   * @return masterAcceptReadRequests
  **/
  @Schema(description = "")
  public Boolean isMasterAcceptReadRequests() {
    return masterAcceptReadRequests;
  }

  public void setMasterAcceptReadRequests(Boolean masterAcceptReadRequests) {
    this.masterAcceptReadRequests = masterAcceptReadRequests;
  }

  public EndpointForDescribeDBEndpointOutput nodeIds(List<String> nodeIds) {
    this.nodeIds = nodeIds;
    return this;
  }

  public EndpointForDescribeDBEndpointOutput addNodeIdsItem(String nodeIdsItem) {
    if (this.nodeIds == null) {
      this.nodeIds = new ArrayList<String>();
    }
    this.nodeIds.add(nodeIdsItem);
    return this;
  }

   /**
   * Get nodeIds
   * @return nodeIds
  **/
  @Schema(description = "")
  public List<String> getNodeIds() {
    return nodeIds;
  }

  public void setNodeIds(List<String> nodeIds) {
    this.nodeIds = nodeIds;
  }

  public EndpointForDescribeDBEndpointOutput readWriteMode(String readWriteMode) {
    this.readWriteMode = readWriteMode;
    return this;
  }

   /**
   * Get readWriteMode
   * @return readWriteMode
  **/
  @Schema(description = "")
  public String getReadWriteMode() {
    return readWriteMode;
  }

  public void setReadWriteMode(String readWriteMode) {
    this.readWriteMode = readWriteMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointForDescribeDBEndpointOutput endpointForDescribeDBEndpointOutput = (EndpointForDescribeDBEndpointOutput) o;
    return Objects.equals(this.addresses, endpointForDescribeDBEndpointOutput.addresses) &&
        Objects.equals(this.autoAddNewNodes, endpointForDescribeDBEndpointOutput.autoAddNewNodes) &&
        Objects.equals(this.connectionPool, endpointForDescribeDBEndpointOutput.connectionPool) &&
        Objects.equals(this.consistLevel, endpointForDescribeDBEndpointOutput.consistLevel) &&
        Objects.equals(this.consistTimeout, endpointForDescribeDBEndpointOutput.consistTimeout) &&
        Objects.equals(this.consistTimeoutAction, endpointForDescribeDBEndpointOutput.consistTimeoutAction) &&
        Objects.equals(this.description, endpointForDescribeDBEndpointOutput.description) &&
        Objects.equals(this.distributedTransaction, endpointForDescribeDBEndpointOutput.distributedTransaction) &&
        Objects.equals(this.endpointId, endpointForDescribeDBEndpointOutput.endpointId) &&
        Objects.equals(this.endpointName, endpointForDescribeDBEndpointOutput.endpointName) &&
        Objects.equals(this.endpointType, endpointForDescribeDBEndpointOutput.endpointType) &&
        Objects.equals(this.masterAcceptReadRequests, endpointForDescribeDBEndpointOutput.masterAcceptReadRequests) &&
        Objects.equals(this.nodeIds, endpointForDescribeDBEndpointOutput.nodeIds) &&
        Objects.equals(this.readWriteMode, endpointForDescribeDBEndpointOutput.readWriteMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, autoAddNewNodes, connectionPool, consistLevel, consistTimeout, consistTimeoutAction, description, distributedTransaction, endpointId, endpointName, endpointType, masterAcceptReadRequests, nodeIds, readWriteMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointForDescribeDBEndpointOutput {\n");
    
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    autoAddNewNodes: ").append(toIndentedString(autoAddNewNodes)).append("\n");
    sb.append("    connectionPool: ").append(toIndentedString(connectionPool)).append("\n");
    sb.append("    consistLevel: ").append(toIndentedString(consistLevel)).append("\n");
    sb.append("    consistTimeout: ").append(toIndentedString(consistTimeout)).append("\n");
    sb.append("    consistTimeoutAction: ").append(toIndentedString(consistTimeoutAction)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    distributedTransaction: ").append(toIndentedString(distributedTransaction)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    endpointName: ").append(toIndentedString(endpointName)).append("\n");
    sb.append("    endpointType: ").append(toIndentedString(endpointType)).append("\n");
    sb.append("    masterAcceptReadRequests: ").append(toIndentedString(masterAcceptReadRequests)).append("\n");
    sb.append("    nodeIds: ").append(toIndentedString(nodeIds)).append("\n");
    sb.append("    readWriteMode: ").append(toIndentedString(readWriteMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
