/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * AccountDBPrivilegeForCreateDBAccountInput
 */



public class AccountDBPrivilegeForCreateDBAccountInput {
  @SerializedName("DBName")
  private String dbName = null;

  @SerializedName("RoleNames")
  private List<String> roleNames = null;

  public AccountDBPrivilegeForCreateDBAccountInput dbName(String dbName) {
    this.dbName = dbName;
    return this;
  }

   /**
   * Get dbName
   * @return dbName
  **/
  @Schema(description = "")
  public String getDbName() {
    return dbName;
  }

  public void setDbName(String dbName) {
    this.dbName = dbName;
  }

  public AccountDBPrivilegeForCreateDBAccountInput roleNames(List<String> roleNames) {
    this.roleNames = roleNames;
    return this;
  }

  public AccountDBPrivilegeForCreateDBAccountInput addRoleNamesItem(String roleNamesItem) {
    if (this.roleNames == null) {
      this.roleNames = new ArrayList<String>();
    }
    this.roleNames.add(roleNamesItem);
    return this;
  }

   /**
   * Get roleNames
   * @return roleNames
  **/
  @Schema(description = "")
  public List<String> getRoleNames() {
    return roleNames;
  }

  public void setRoleNames(List<String> roleNames) {
    this.roleNames = roleNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountDBPrivilegeForCreateDBAccountInput accountDBPrivilegeForCreateDBAccountInput = (AccountDBPrivilegeForCreateDBAccountInput) o;
    return Objects.equals(this.dbName, accountDBPrivilegeForCreateDBAccountInput.dbName) &&
        Objects.equals(this.roleNames, accountDBPrivilegeForCreateDBAccountInput.roleNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dbName, roleNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountDBPrivilegeForCreateDBAccountInput {\n");
    
    sb.append("    dbName: ").append(toIndentedString(dbName)).append("\n");
    sb.append("    roleNames: ").append(toIndentedString(roleNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
