/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.byteplus.mongodb.model.AccountDBPrivilegeForCreateDBAccountInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * CreateDBAccountRequest
 */



public class CreateDBAccountRequest {
  @SerializedName("AccountDBPrivileges")
  private List<AccountDBPrivilegeForCreateDBAccountInput> accountDBPrivileges = null;

  @SerializedName("AccountDesc")
  private String accountDesc = null;

  @SerializedName("AccountName")
  private String accountName = null;

  @SerializedName("AccountPassword")
  private String accountPassword = null;

  @SerializedName("AuthDB")
  private String authDB = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  public CreateDBAccountRequest accountDBPrivileges(List<AccountDBPrivilegeForCreateDBAccountInput> accountDBPrivileges) {
    this.accountDBPrivileges = accountDBPrivileges;
    return this;
  }

  public CreateDBAccountRequest addAccountDBPrivilegesItem(AccountDBPrivilegeForCreateDBAccountInput accountDBPrivilegesItem) {
    if (this.accountDBPrivileges == null) {
      this.accountDBPrivileges = new ArrayList<AccountDBPrivilegeForCreateDBAccountInput>();
    }
    this.accountDBPrivileges.add(accountDBPrivilegesItem);
    return this;
  }

   /**
   * Get accountDBPrivileges
   * @return accountDBPrivileges
  **/
  @Valid
  @Schema(description = "")
  public List<AccountDBPrivilegeForCreateDBAccountInput> getAccountDBPrivileges() {
    return accountDBPrivileges;
  }

  public void setAccountDBPrivileges(List<AccountDBPrivilegeForCreateDBAccountInput> accountDBPrivileges) {
    this.accountDBPrivileges = accountDBPrivileges;
  }

  public CreateDBAccountRequest accountDesc(String accountDesc) {
    this.accountDesc = accountDesc;
    return this;
  }

   /**
   * Get accountDesc
   * @return accountDesc
  **/
  @Schema(description = "")
  public String getAccountDesc() {
    return accountDesc;
  }

  public void setAccountDesc(String accountDesc) {
    this.accountDesc = accountDesc;
  }

  public CreateDBAccountRequest accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public CreateDBAccountRequest accountPassword(String accountPassword) {
    this.accountPassword = accountPassword;
    return this;
  }

   /**
   * Get accountPassword
   * @return accountPassword
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getAccountPassword() {
    return accountPassword;
  }

  public void setAccountPassword(String accountPassword) {
    this.accountPassword = accountPassword;
  }

  public CreateDBAccountRequest authDB(String authDB) {
    this.authDB = authDB;
    return this;
  }

   /**
   * Get authDB
   * @return authDB
  **/
  @Schema(description = "")
  public String getAuthDB() {
    return authDB;
  }

  public void setAuthDB(String authDB) {
    this.authDB = authDB;
  }

  public CreateDBAccountRequest instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDBAccountRequest createDBAccountRequest = (CreateDBAccountRequest) o;
    return Objects.equals(this.accountDBPrivileges, createDBAccountRequest.accountDBPrivileges) &&
        Objects.equals(this.accountDesc, createDBAccountRequest.accountDesc) &&
        Objects.equals(this.accountName, createDBAccountRequest.accountName) &&
        Objects.equals(this.accountPassword, createDBAccountRequest.accountPassword) &&
        Objects.equals(this.authDB, createDBAccountRequest.authDB) &&
        Objects.equals(this.instanceId, createDBAccountRequest.instanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountDBPrivileges, accountDesc, accountName, accountPassword, authDB, instanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDBAccountRequest {\n");
    
    sb.append("    accountDBPrivileges: ").append(toIndentedString(accountDBPrivileges)).append("\n");
    sb.append("    accountDesc: ").append(toIndentedString(accountDesc)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountPassword: ").append(toIndentedString(accountPassword)).append("\n");
    sb.append("    authDB: ").append(toIndentedString(authDB)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
