/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeNormalLogsRequest
 */



public class DescribeNormalLogsRequest {
  @SerializedName("Context")
  private String context = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("Keys")
  private String keys = null;

  @SerializedName("Limit")
  private Long limit = null;

  /**
   * Gets or Sets logLevel
   */
  @JsonAdapter(LogLevelEnum.Adapter.class)
  public enum LogLevelEnum {
    @SerializedName("ErrorLog")
    ERRORLOG("ErrorLog"),
    @SerializedName("RunningLog")
    RUNNINGLOG("RunningLog");

    private String value;

    LogLevelEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static LogLevelEnum fromValue(String input) {
      for (LogLevelEnum b : LogLevelEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<LogLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LogLevelEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public LogLevelEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return LogLevelEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("LogLevel")
  private LogLevelEnum logLevel = null;

  @SerializedName("PodName")
  private String podName = null;

  @SerializedName("QueryEndTime")
  private String queryEndTime = null;

  @SerializedName("QueryStartTime")
  private String queryStartTime = null;

  /**
   * Gets or Sets sort
   */
  @JsonAdapter(SortEnum.Adapter.class)
  public enum SortEnum {
    @SerializedName("ASC")
    ASC("ASC"),
    @SerializedName("DESC")
    DESC("DESC");

    private String value;

    SortEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SortEnum fromValue(String input) {
      for (SortEnum b : SortEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SortEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SortEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SortEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SortEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("Sort")
  private SortEnum sort = null;

  public DescribeNormalLogsRequest context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public DescribeNormalLogsRequest instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public DescribeNormalLogsRequest keys(String keys) {
    this.keys = keys;
    return this;
  }

   /**
   * Get keys
   * @return keys
  **/
  @Schema(description = "")
  public String getKeys() {
    return keys;
  }

  public void setKeys(String keys) {
    this.keys = keys;
  }

  public DescribeNormalLogsRequest limit(Long limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public DescribeNormalLogsRequest logLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
    return this;
  }

   /**
   * Get logLevel
   * @return logLevel
  **/
  @Schema(description = "")
  public LogLevelEnum getLogLevel() {
    return logLevel;
  }

  public void setLogLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
  }

  public DescribeNormalLogsRequest podName(String podName) {
    this.podName = podName;
    return this;
  }

   /**
   * Get podName
   * @return podName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getPodName() {
    return podName;
  }

  public void setPodName(String podName) {
    this.podName = podName;
  }

  public DescribeNormalLogsRequest queryEndTime(String queryEndTime) {
    this.queryEndTime = queryEndTime;
    return this;
  }

   /**
   * Get queryEndTime
   * @return queryEndTime
  **/
  @Schema(description = "")
  public String getQueryEndTime() {
    return queryEndTime;
  }

  public void setQueryEndTime(String queryEndTime) {
    this.queryEndTime = queryEndTime;
  }

  public DescribeNormalLogsRequest queryStartTime(String queryStartTime) {
    this.queryStartTime = queryStartTime;
    return this;
  }

   /**
   * Get queryStartTime
   * @return queryStartTime
  **/
  @Schema(description = "")
  public String getQueryStartTime() {
    return queryStartTime;
  }

  public void setQueryStartTime(String queryStartTime) {
    this.queryStartTime = queryStartTime;
  }

  public DescribeNormalLogsRequest sort(SortEnum sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public SortEnum getSort() {
    return sort;
  }

  public void setSort(SortEnum sort) {
    this.sort = sort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeNormalLogsRequest describeNormalLogsRequest = (DescribeNormalLogsRequest) o;
    return Objects.equals(this.context, describeNormalLogsRequest.context) &&
        Objects.equals(this.instanceId, describeNormalLogsRequest.instanceId) &&
        Objects.equals(this.keys, describeNormalLogsRequest.keys) &&
        Objects.equals(this.limit, describeNormalLogsRequest.limit) &&
        Objects.equals(this.logLevel, describeNormalLogsRequest.logLevel) &&
        Objects.equals(this.podName, describeNormalLogsRequest.podName) &&
        Objects.equals(this.queryEndTime, describeNormalLogsRequest.queryEndTime) &&
        Objects.equals(this.queryStartTime, describeNormalLogsRequest.queryStartTime) &&
        Objects.equals(this.sort, describeNormalLogsRequest.sort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, instanceId, keys, limit, logLevel, podName, queryEndTime, queryStartTime, sort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeNormalLogsRequest {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    logLevel: ").append(toIndentedString(logLevel)).append("\n");
    sb.append("    podName: ").append(toIndentedString(podName)).append("\n");
    sb.append("    queryEndTime: ").append(toIndentedString(queryEndTime)).append("\n");
    sb.append("    queryStartTime: ").append(toIndentedString(queryStartTime)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
