/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeDBInstanceBackupPolicyResponse
 */



public class DescribeDBInstanceBackupPolicyResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("AutoBackup")
  private String autoBackup = null;

  @SerializedName("DataBackupRetentionDay")
  private Integer dataBackupRetentionDay = null;

  @SerializedName("DataFullBackupPeriods")
  private List<String> dataFullBackupPeriods = null;

  @SerializedName("DataFullBackupTime")
  private String dataFullBackupTime = null;

  @SerializedName("EnableBackupEncrypt")
  private Boolean enableBackupEncrypt = null;

  public DescribeDBInstanceBackupPolicyResponse autoBackup(String autoBackup) {
    this.autoBackup = autoBackup;
    return this;
  }

   /**
   * Get autoBackup
   * @return autoBackup
  **/
  @Schema(description = "")
  public String getAutoBackup() {
    return autoBackup;
  }

  public void setAutoBackup(String autoBackup) {
    this.autoBackup = autoBackup;
  }

  public DescribeDBInstanceBackupPolicyResponse dataBackupRetentionDay(Integer dataBackupRetentionDay) {
    this.dataBackupRetentionDay = dataBackupRetentionDay;
    return this;
  }

   /**
   * Get dataBackupRetentionDay
   * @return dataBackupRetentionDay
  **/
  @Schema(description = "")
  public Integer getDataBackupRetentionDay() {
    return dataBackupRetentionDay;
  }

  public void setDataBackupRetentionDay(Integer dataBackupRetentionDay) {
    this.dataBackupRetentionDay = dataBackupRetentionDay;
  }

  public DescribeDBInstanceBackupPolicyResponse dataFullBackupPeriods(List<String> dataFullBackupPeriods) {
    this.dataFullBackupPeriods = dataFullBackupPeriods;
    return this;
  }

  public DescribeDBInstanceBackupPolicyResponse addDataFullBackupPeriodsItem(String dataFullBackupPeriodsItem) {
    if (this.dataFullBackupPeriods == null) {
      this.dataFullBackupPeriods = new ArrayList<String>();
    }
    this.dataFullBackupPeriods.add(dataFullBackupPeriodsItem);
    return this;
  }

   /**
   * Get dataFullBackupPeriods
   * @return dataFullBackupPeriods
  **/
  @Schema(description = "")
  public List<String> getDataFullBackupPeriods() {
    return dataFullBackupPeriods;
  }

  public void setDataFullBackupPeriods(List<String> dataFullBackupPeriods) {
    this.dataFullBackupPeriods = dataFullBackupPeriods;
  }

  public DescribeDBInstanceBackupPolicyResponse dataFullBackupTime(String dataFullBackupTime) {
    this.dataFullBackupTime = dataFullBackupTime;
    return this;
  }

   /**
   * Get dataFullBackupTime
   * @return dataFullBackupTime
  **/
  @Schema(description = "")
  public String getDataFullBackupTime() {
    return dataFullBackupTime;
  }

  public void setDataFullBackupTime(String dataFullBackupTime) {
    this.dataFullBackupTime = dataFullBackupTime;
  }

  public DescribeDBInstanceBackupPolicyResponse enableBackupEncrypt(Boolean enableBackupEncrypt) {
    this.enableBackupEncrypt = enableBackupEncrypt;
    return this;
  }

   /**
   * Get enableBackupEncrypt
   * @return enableBackupEncrypt
  **/
  @Schema(description = "")
  public Boolean isEnableBackupEncrypt() {
    return enableBackupEncrypt;
  }

  public void setEnableBackupEncrypt(Boolean enableBackupEncrypt) {
    this.enableBackupEncrypt = enableBackupEncrypt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeDBInstanceBackupPolicyResponse describeDBInstanceBackupPolicyResponse = (DescribeDBInstanceBackupPolicyResponse) o;
    return Objects.equals(this.autoBackup, describeDBInstanceBackupPolicyResponse.autoBackup) &&
        Objects.equals(this.dataBackupRetentionDay, describeDBInstanceBackupPolicyResponse.dataBackupRetentionDay) &&
        Objects.equals(this.dataFullBackupPeriods, describeDBInstanceBackupPolicyResponse.dataFullBackupPeriods) &&
        Objects.equals(this.dataFullBackupTime, describeDBInstanceBackupPolicyResponse.dataFullBackupTime) &&
        Objects.equals(this.enableBackupEncrypt, describeDBInstanceBackupPolicyResponse.enableBackupEncrypt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoBackup, dataBackupRetentionDay, dataFullBackupPeriods, dataFullBackupTime, enableBackupEncrypt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeDBInstanceBackupPolicyResponse {\n");
    
    sb.append("    autoBackup: ").append(toIndentedString(autoBackup)).append("\n");
    sb.append("    dataBackupRetentionDay: ").append(toIndentedString(dataBackupRetentionDay)).append("\n");
    sb.append("    dataFullBackupPeriods: ").append(toIndentedString(dataFullBackupPeriods)).append("\n");
    sb.append("    dataFullBackupTime: ").append(toIndentedString(dataFullBackupTime)).append("\n");
    sb.append("    enableBackupEncrypt: ").append(toIndentedString(enableBackupEncrypt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
