/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeSlowLogsRequest
 */



public class DescribeSlowLogsRequest {
  @SerializedName("Context")
  private String context = null;

  @SerializedName("DBName")
  private String dbName = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("Keys")
  private String keys = null;

  @SerializedName("Limit")
  private Long limit = null;

  @SerializedName("PodName")
  private String podName = null;

  @SerializedName("QueryEndTime")
  private String queryEndTime = null;

  @SerializedName("QueryStartTime")
  private String queryStartTime = null;

  /**
   * Gets or Sets sort
   */
  @JsonAdapter(SortEnum.Adapter.class)
  public enum SortEnum {
    @SerializedName("ASC")
    ASC("ASC"),
    @SerializedName("DESC")
    DESC("DESC");

    private String value;

    SortEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SortEnum fromValue(String input) {
      for (SortEnum b : SortEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SortEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SortEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SortEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SortEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("Sort")
  private SortEnum sort = null;

  public DescribeSlowLogsRequest context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public DescribeSlowLogsRequest dbName(String dbName) {
    this.dbName = dbName;
    return this;
  }

   /**
   * Get dbName
   * @return dbName
  **/
  @Schema(description = "")
  public String getDbName() {
    return dbName;
  }

  public void setDbName(String dbName) {
    this.dbName = dbName;
  }

  public DescribeSlowLogsRequest instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public DescribeSlowLogsRequest keys(String keys) {
    this.keys = keys;
    return this;
  }

   /**
   * Get keys
   * @return keys
  **/
  @Schema(description = "")
  public String getKeys() {
    return keys;
  }

  public void setKeys(String keys) {
    this.keys = keys;
  }

  public DescribeSlowLogsRequest limit(Long limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public DescribeSlowLogsRequest podName(String podName) {
    this.podName = podName;
    return this;
  }

   /**
   * Get podName
   * @return podName
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getPodName() {
    return podName;
  }

  public void setPodName(String podName) {
    this.podName = podName;
  }

  public DescribeSlowLogsRequest queryEndTime(String queryEndTime) {
    this.queryEndTime = queryEndTime;
    return this;
  }

   /**
   * Get queryEndTime
   * @return queryEndTime
  **/
  @Schema(description = "")
  public String getQueryEndTime() {
    return queryEndTime;
  }

  public void setQueryEndTime(String queryEndTime) {
    this.queryEndTime = queryEndTime;
  }

  public DescribeSlowLogsRequest queryStartTime(String queryStartTime) {
    this.queryStartTime = queryStartTime;
    return this;
  }

   /**
   * Get queryStartTime
   * @return queryStartTime
  **/
  @Schema(description = "")
  public String getQueryStartTime() {
    return queryStartTime;
  }

  public void setQueryStartTime(String queryStartTime) {
    this.queryStartTime = queryStartTime;
  }

  public DescribeSlowLogsRequest sort(SortEnum sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public SortEnum getSort() {
    return sort;
  }

  public void setSort(SortEnum sort) {
    this.sort = sort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeSlowLogsRequest describeSlowLogsRequest = (DescribeSlowLogsRequest) o;
    return Objects.equals(this.context, describeSlowLogsRequest.context) &&
        Objects.equals(this.dbName, describeSlowLogsRequest.dbName) &&
        Objects.equals(this.instanceId, describeSlowLogsRequest.instanceId) &&
        Objects.equals(this.keys, describeSlowLogsRequest.keys) &&
        Objects.equals(this.limit, describeSlowLogsRequest.limit) &&
        Objects.equals(this.podName, describeSlowLogsRequest.podName) &&
        Objects.equals(this.queryEndTime, describeSlowLogsRequest.queryEndTime) &&
        Objects.equals(this.queryStartTime, describeSlowLogsRequest.queryStartTime) &&
        Objects.equals(this.sort, describeSlowLogsRequest.sort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, dbName, instanceId, keys, limit, podName, queryEndTime, queryStartTime, sort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeSlowLogsRequest {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    dbName: ").append(toIndentedString(dbName)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    podName: ").append(toIndentedString(podName)).append("\n");
    sb.append("    queryEndTime: ").append(toIndentedString(queryEndTime)).append("\n");
    sb.append("    queryStartTime: ").append(toIndentedString(queryStartTime)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
