/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeDBInstanceBackupURLResponse
 */



public class DescribeDBInstanceBackupURLResponse extends com.byteplus.model.AbstractResponse {
  @SerializedName("BackupDownloadLink")
  private String backupDownloadLink = null;

  @SerializedName("BackupId")
  private String backupId = null;

  @SerializedName("DownloadProgress")
  private Integer downloadProgress = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("LinkExpiredTime")
  private String linkExpiredTime = null;

  @SerializedName("PrivateDownloadLink")
  private String privateDownloadLink = null;

  public DescribeDBInstanceBackupURLResponse backupDownloadLink(String backupDownloadLink) {
    this.backupDownloadLink = backupDownloadLink;
    return this;
  }

   /**
   * Get backupDownloadLink
   * @return backupDownloadLink
  **/
  @Schema(description = "")
  public String getBackupDownloadLink() {
    return backupDownloadLink;
  }

  public void setBackupDownloadLink(String backupDownloadLink) {
    this.backupDownloadLink = backupDownloadLink;
  }

  public DescribeDBInstanceBackupURLResponse backupId(String backupId) {
    this.backupId = backupId;
    return this;
  }

   /**
   * Get backupId
   * @return backupId
  **/
  @Schema(description = "")
  public String getBackupId() {
    return backupId;
  }

  public void setBackupId(String backupId) {
    this.backupId = backupId;
  }

  public DescribeDBInstanceBackupURLResponse downloadProgress(Integer downloadProgress) {
    this.downloadProgress = downloadProgress;
    return this;
  }

   /**
   * Get downloadProgress
   * @return downloadProgress
  **/
  @Schema(description = "")
  public Integer getDownloadProgress() {
    return downloadProgress;
  }

  public void setDownloadProgress(Integer downloadProgress) {
    this.downloadProgress = downloadProgress;
  }

  public DescribeDBInstanceBackupURLResponse instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @Schema(description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public DescribeDBInstanceBackupURLResponse linkExpiredTime(String linkExpiredTime) {
    this.linkExpiredTime = linkExpiredTime;
    return this;
  }

   /**
   * Get linkExpiredTime
   * @return linkExpiredTime
  **/
  @Schema(description = "")
  public String getLinkExpiredTime() {
    return linkExpiredTime;
  }

  public void setLinkExpiredTime(String linkExpiredTime) {
    this.linkExpiredTime = linkExpiredTime;
  }

  public DescribeDBInstanceBackupURLResponse privateDownloadLink(String privateDownloadLink) {
    this.privateDownloadLink = privateDownloadLink;
    return this;
  }

   /**
   * Get privateDownloadLink
   * @return privateDownloadLink
  **/
  @Schema(description = "")
  public String getPrivateDownloadLink() {
    return privateDownloadLink;
  }

  public void setPrivateDownloadLink(String privateDownloadLink) {
    this.privateDownloadLink = privateDownloadLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeDBInstanceBackupURLResponse describeDBInstanceBackupURLResponse = (DescribeDBInstanceBackupURLResponse) o;
    return Objects.equals(this.backupDownloadLink, describeDBInstanceBackupURLResponse.backupDownloadLink) &&
        Objects.equals(this.backupId, describeDBInstanceBackupURLResponse.backupId) &&
        Objects.equals(this.downloadProgress, describeDBInstanceBackupURLResponse.downloadProgress) &&
        Objects.equals(this.instanceId, describeDBInstanceBackupURLResponse.instanceId) &&
        Objects.equals(this.linkExpiredTime, describeDBInstanceBackupURLResponse.linkExpiredTime) &&
        Objects.equals(this.privateDownloadLink, describeDBInstanceBackupURLResponse.privateDownloadLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupDownloadLink, backupId, downloadProgress, instanceId, linkExpiredTime, privateDownloadLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeDBInstanceBackupURLResponse {\n");
    
    sb.append("    backupDownloadLink: ").append(toIndentedString(backupDownloadLink)).append("\n");
    sb.append("    backupId: ").append(toIndentedString(backupId)).append("\n");
    sb.append("    downloadProgress: ").append(toIndentedString(downloadProgress)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    linkExpiredTime: ").append(toIndentedString(linkExpiredTime)).append("\n");
    sb.append("    privateDownloadLink: ").append(toIndentedString(privateDownloadLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
