/*
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.byteplus.mongodb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ModifyDBInstanceBackupPolicyRequest
 */



public class ModifyDBInstanceBackupPolicyRequest {
  @SerializedName("DataBackupRetentionDay")
  private Integer dataBackupRetentionDay = null;

  @SerializedName("DataFullBackupPeriods")
  private List<String> dataFullBackupPeriods = null;

  @SerializedName("DataFullBackupTime")
  private String dataFullBackupTime = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  public ModifyDBInstanceBackupPolicyRequest dataBackupRetentionDay(Integer dataBackupRetentionDay) {
    this.dataBackupRetentionDay = dataBackupRetentionDay;
    return this;
  }

   /**
   * Get dataBackupRetentionDay
   * @return dataBackupRetentionDay
  **/
  @Schema(description = "")
  public Integer getDataBackupRetentionDay() {
    return dataBackupRetentionDay;
  }

  public void setDataBackupRetentionDay(Integer dataBackupRetentionDay) {
    this.dataBackupRetentionDay = dataBackupRetentionDay;
  }

  public ModifyDBInstanceBackupPolicyRequest dataFullBackupPeriods(List<String> dataFullBackupPeriods) {
    this.dataFullBackupPeriods = dataFullBackupPeriods;
    return this;
  }

  public ModifyDBInstanceBackupPolicyRequest addDataFullBackupPeriodsItem(String dataFullBackupPeriodsItem) {
    if (this.dataFullBackupPeriods == null) {
      this.dataFullBackupPeriods = new ArrayList<String>();
    }
    this.dataFullBackupPeriods.add(dataFullBackupPeriodsItem);
    return this;
  }

   /**
   * Get dataFullBackupPeriods
   * @return dataFullBackupPeriods
  **/
  @Schema(description = "")
  public List<String> getDataFullBackupPeriods() {
    return dataFullBackupPeriods;
  }

  public void setDataFullBackupPeriods(List<String> dataFullBackupPeriods) {
    this.dataFullBackupPeriods = dataFullBackupPeriods;
  }

  public ModifyDBInstanceBackupPolicyRequest dataFullBackupTime(String dataFullBackupTime) {
    this.dataFullBackupTime = dataFullBackupTime;
    return this;
  }

   /**
   * Get dataFullBackupTime
   * @return dataFullBackupTime
  **/
  @Schema(description = "")
  public String getDataFullBackupTime() {
    return dataFullBackupTime;
  }

  public void setDataFullBackupTime(String dataFullBackupTime) {
    this.dataFullBackupTime = dataFullBackupTime;
  }

  public ModifyDBInstanceBackupPolicyRequest instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyDBInstanceBackupPolicyRequest modifyDBInstanceBackupPolicyRequest = (ModifyDBInstanceBackupPolicyRequest) o;
    return Objects.equals(this.dataBackupRetentionDay, modifyDBInstanceBackupPolicyRequest.dataBackupRetentionDay) &&
        Objects.equals(this.dataFullBackupPeriods, modifyDBInstanceBackupPolicyRequest.dataFullBackupPeriods) &&
        Objects.equals(this.dataFullBackupTime, modifyDBInstanceBackupPolicyRequest.dataFullBackupTime) &&
        Objects.equals(this.instanceId, modifyDBInstanceBackupPolicyRequest.instanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataBackupRetentionDay, dataFullBackupPeriods, dataFullBackupTime, instanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyDBInstanceBackupPolicyRequest {\n");
    
    sb.append("    dataBackupRetentionDay: ").append(toIndentedString(dataBackupRetentionDay)).append("\n");
    sb.append("    dataFullBackupPeriods: ").append(toIndentedString(dataFullBackupPeriods)).append("\n");
    sb.append("    dataFullBackupTime: ").append(toIndentedString(dataFullBackupTime)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
